function __global_object_depths() {
	// Initialise the global array that allows the lookup of the depth of a given object
	// GM2.0 does not have a depth on objects so on import from 1.x a global array is created
	// NOTE: MacroExpansion is used to insert the array initialisation at import time
	gml_pragma( "global", "__global_object_depths()");

	// insert the generated arrays here
	global.__objectDepths[0] = 0; // oMenu
	global.__objectDepths[1] = 0; // oDrawnSprite
	global.__objectDepths[2] = 0; // oCharacter
	global.__objectDepths[3] = 0; // oEnemy
	global.__objectDepths[4] = 0; // oLadder
	global.__objectDepths[5] = 0; // oMoveableSolid
	global.__objectDepths[6] = 0; // oMovingSolid
	global.__objectDepths[7] = 0; // oPlatform
	global.__objectDepths[8] = 100; // oSolid
	global.__objectDepths[9] = 0; // oBackdrop
	global.__objectDepths[10] = 0; // oForeground
	global.__objectDepths[11] = 0; // oWater
	global.__objectDepths[12] = 0; // oItem
	global.__objectDepths[13] = 101; // oTreasure
	global.__objectDepths[14] = 0; // oDetritus
	global.__objectDepths[15] = 0; // oRubblePiece
	global.__objectDepths[16] = 0; // oFrill
	global.__objectDepths[17] = 0; // oGhost
	global.__objectDepths[18] = 40; // oBat
	global.__objectDepths[19] = 40; // oScarab
	global.__objectDepths[20] = 60; // oSnake
	global.__objectDepths[21] = 40; // oSpider
	global.__objectDepths[22] = 40; // oSpiderHang
	global.__objectDepths[23] = 40; // oGiantSpiderHang
	global.__objectDepths[24] = 40; // oGiantSpider
	global.__objectDepths[25] = 60; // oSkeleton
	global.__objectDepths[26] = 40; // oFrog
	global.__objectDepths[27] = 40; // oFireFrog
	global.__objectDepths[28] = 40; // oZombie
	global.__objectDepths[29] = 60; // oVampire
	global.__objectDepths[30] = 40; // oPiranha
	global.__objectDepths[31] = 40; // oJaws
	global.__objectDepths[32] = 40; // oDeadFish
	global.__objectDepths[33] = 60; // oManTrap
	global.__objectDepths[34] = 40; // oMonkey
	global.__objectDepths[35] = 60; // oYeti
	global.__objectDepths[36] = 60; // oYetiKing
	global.__objectDepths[37] = 40; // oUFO
	global.__objectDepths[38] = 0; // oUFOCrash
	global.__objectDepths[39] = 60; // oAlienEject
	global.__objectDepths[40] = 60; // oAlien
	global.__objectDepths[41] = 60; // oAlienBoss
	global.__objectDepths[42] = 100; // oBarrierEmitter
	global.__objectDepths[43] = 108; // oBarrier
	global.__objectDepths[44] = 60; // oCaveman
	global.__objectDepths[45] = 60; // oHawkman
	global.__objectDepths[46] = 1; // oMagma
	global.__objectDepths[47] = 2; // oMagmaTrail
	global.__objectDepths[48] = 60; // oMagmaMan
	global.__objectDepths[49] = 60; // oTombLord
	global.__objectDepths[50] = 40; // oOlmec
	global.__objectDepths[51] = 60; // oCavemanWorship
	global.__objectDepths[52] = 0; // oHawkmanWorship
	global.__objectDepths[53] = 1; // oOlmecDebris
	global.__objectDepths[54] = 0; // oOlmecSlam
	global.__objectDepths[55] = 0; // oEnemySight
	global.__objectDepths[56] = 0; // oEntranceCheck
	global.__objectDepths[57] = 100; // oRopeThrow
	global.__objectDepths[58] = 200; // oRope
	global.__objectDepths[59] = 200; // oRopeTop
	global.__objectDepths[60] = 1; // oWhip
	global.__objectDepths[61] = 1; // oWhipPre
	global.__objectDepths[62] = 1; // oMachetePre
	global.__objectDepths[63] = 1; // oSlash
	global.__objectDepths[64] = 1; // oMattockPre
	global.__objectDepths[65] = 1; // oMattockHit
	global.__objectDepths[66] = 99; // oBomb
	global.__objectDepths[67] = 99; // oBall
	global.__objectDepths[68] = 1; // oChain
	global.__objectDepths[69] = 99; // oBall2
	global.__objectDepths[70] = 1; // oChain2
	global.__objectDepths[71] = 99; // oFireFrogBomb
	global.__objectDepths[72] = 100; // oRock
	global.__objectDepths[73] = 100; // oDice
	global.__objectDepths[74] = 100; // oMattockHead
	global.__objectDepths[75] = 100; // oBasketball
	global.__objectDepths[76] = 101; // oShotgun
	global.__objectDepths[77] = 101; // oPistol
	global.__objectDepths[78] = 101; // oWebCannon
	global.__objectDepths[79] = 101; // oTeleporter
	global.__objectDepths[80] = 101; // oBow
	global.__objectDepths[81] = 101; // oMachete
	global.__objectDepths[82] = 101; // oSceptre
	global.__objectDepths[83] = 101; // oMattock
	global.__objectDepths[84] = 100; // oJar
	global.__objectDepths[85] = 100; // oSkull
	global.__objectDepths[86] = 100; // oArrow
	global.__objectDepths[87] = 100; // oFishBone
	global.__objectDepths[88] = 30; // oFlare
	global.__objectDepths[89] = 100; // oGoldIdol
	global.__objectDepths[90] = 100; // oCrystalSkull
	global.__objectDepths[91] = 100; // oLampItem
	global.__objectDepths[92] = 100; // oLampRedItem
	global.__objectDepths[93] = 900; // oParachute
	global.__objectDepths[94] = 99999999; // oCaveBG
	global.__objectDepths[95] = 998; // oCaveBG2
	global.__objectDepths[96] = 998; // oCaveBGEntrance
	global.__objectDepths[97] = 9000; // oEntrance
	global.__objectDepths[98] = 10000; // oGoldDoor
	global.__objectDepths[99] = 9000; // oExit
	global.__objectDepths[100] = 9000; // oXMarket
	global.__objectDepths[101] = 9000; // oXGold
	global.__objectDepths[102] = 998; // oMsgSign
	global.__objectDepths[103] = 100; // oBrick
	global.__objectDepths[104] = 110; // oBrickSmooth
	global.__objectDepths[105] = 110; // oSign
	global.__objectDepths[106] = 201; // oLamp
	global.__objectDepths[107] = 201; // oLampRed
	global.__objectDepths[108] = 100; // oLush
	global.__objectDepths[109] = 8999; // oTikiTorch
	global.__objectDepths[110] = 2; // oTree
	global.__objectDepths[111] = 2; // oTreeTile
	global.__objectDepths[112] = 1; // oLeaves
	global.__objectDepths[113] = 1; // oLeavesTile
	global.__objectDepths[114] = 2; // oTreeBranch
	global.__objectDepths[115] = 2; // oTreeBranchTile
	global.__objectDepths[116] = 100; // oDark
	global.__objectDepths[117] = 100; // oDarkFall
	global.__objectDepths[118] = 100; // oAlienShip
	global.__objectDepths[119] = 100; // oAlienShipFloor
	global.__objectDepths[120] = 100; // oMoai
	global.__objectDepths[121] = 100; // oMoai2
	global.__objectDepths[122] = 100; // oMoai3
	global.__objectDepths[123] = 100; // oMoaiInside
	global.__objectDepths[124] = 100; // oTemple
	global.__objectDepths[125] = 60; // oTempleFake
	global.__objectDepths[126] = 100; // oGold
	global.__objectDepths[127] = 100; // oGoldBig
	global.__objectDepths[128] = 110; // oBlock
	global.__objectDepths[129] = 110; // oXocBlock
	global.__objectDepths[130] = 110; // oGrave
	global.__objectDepths[131] = 110; // oAltarLeft
	global.__objectDepths[132] = 110; // oAltarRight
	global.__objectDepths[133] = 110; // oSacAltarLeft
	global.__objectDepths[134] = 110; // oSacAltarRight
	global.__objectDepths[135] = 997; // oKaliHead
	global.__objectDepths[136] = 110; // oLavaSolid
	global.__objectDepths[137] = 110; // oPushBlock
	global.__objectDepths[138] = 110; // oIceBlock
	global.__objectDepths[139] = 110; // oIce
	global.__objectDepths[140] = 110; // oIceBottom
	global.__objectDepths[141] = 110; // oThinIce
	global.__objectDepths[142] = 100; // oFrozenCaveman
	global.__objectDepths[143] = 1; // oSplash
	global.__objectDepths[144] = 9003; // oWaterSwim
	global.__objectDepths[145] = 20; // oLava
	global.__objectDepths[146] = 1000; // oLadderOrange
	global.__objectDepths[147] = 1000; // oLadderTop
	global.__objectDepths[148] = 1000; // oVine
	global.__objectDepths[149] = 1000; // oVineTop
	global.__objectDepths[150] = 100; // oHardBlock
	global.__objectDepths[151] = 999999; // oBlackFadeUp
	global.__objectDepths[152] = 0; // oCaveLeft
	global.__objectDepths[153] = 0; // oCaveRight
	global.__objectDepths[154] = 900; // oFakeBones
	global.__objectDepths[155] = 900; // oBones
	global.__objectDepths[156] = 900; // oParaUsed
	global.__objectDepths[157] = 900; // oChest
	global.__objectDepths[158] = 900; // oLockedChest
	global.__objectDepths[159] = 101; // oKey
	global.__objectDepths[160] = 900; // oCrate
	global.__objectDepths[161] = 900; // oFlareCrate
	global.__objectDepths[162] = 900; // oFireFrogArmed
	global.__objectDepths[163] = 100; // oBombBag
	global.__objectDepths[164] = 100; // oBombBox
	global.__objectDepths[165] = 100; // oPaste
	global.__objectDepths[166] = 100; // oRopePile
	global.__objectDepths[167] = 100; // oParaPickup
	global.__objectDepths[168] = 100; // oCompass
	global.__objectDepths[169] = 100; // oSpringShoes
	global.__objectDepths[170] = 100; // oSpikeShoes
	global.__objectDepths[171] = 100; // oJordans
	global.__objectDepths[172] = 100; // oSpectacles
	global.__objectDepths[173] = 100; // oUdjatEye
	global.__objectDepths[174] = 100; // oCrown
	global.__objectDepths[175] = 100; // oKapala
	global.__objectDepths[176] = 101; // oAnkh
	global.__objectDepths[177] = 100; // oGloves
	global.__objectDepths[178] = 100; // oMitt
	global.__objectDepths[179] = 100; // oJetpack
	global.__objectDepths[180] = 100; // oCapePickup
	global.__objectDepths[181] = 100; // oCape
	global.__objectDepths[182] = 100; // oRopeBag
	global.__objectDepths[183] = 100; // oGoldChunk
	global.__objectDepths[184] = 100; // oGoldNugget
	global.__objectDepths[185] = 100; // oGoldBar
	global.__objectDepths[186] = 100; // oGoldBars
	global.__objectDepths[187] = 101; // oEmerald
	global.__objectDepths[188] = 101; // oEmeraldBig
	global.__objectDepths[189] = 101; // oSapphire
	global.__objectDepths[190] = 101; // oSapphireBig
	global.__objectDepths[191] = 101; // oRuby
	global.__objectDepths[192] = 101; // oRubyBig
	global.__objectDepths[193] = 101; // oDiamond
	global.__objectDepths[194] = 1; // oSmallCollect
	global.__objectDepths[195] = 1; // oBigCollect
	global.__objectDepths[196] = 1; // oHeart
	global.__objectDepths[197] = 1; // oItemsGet
	global.__objectDepths[198] = 1; // oBlood
	global.__objectDepths[199] = 1; // oBloodTrail
	global.__objectDepths[200] = 1; // oBloodSpark
	global.__objectDepths[201] = 1; // oDrip
	global.__objectDepths[202] = 1; // oLavaDrip
	global.__objectDepths[203] = 1; // oLeaf
	global.__objectDepths[204] = 1; // oRubble
	global.__objectDepths[205] = 1; // oRubbleSmall
	global.__objectDepths[206] = 1; // oRubbleDark
	global.__objectDepths[207] = 1; // oRubbleDarkSmall
	global.__objectDepths[208] = 1; // oBubble
	global.__objectDepths[209] = 1; // oSmokePuff
	global.__objectDepths[210] = 1; // oPoof
	global.__objectDepths[211] = 1; // oBone
	global.__objectDepths[212] = 999; // oBurn
	global.__objectDepths[213] = 99; // oRopeBurn
	global.__objectDepths[214] = 1; // oFlame
	global.__objectDepths[215] = 1; // oFlameTrail
	global.__objectDepths[216] = 1; // oVolcanoFlame
	global.__objectDepths[217] = 1; // oExplosion
	global.__objectDepths[218] = 0; // oShotgunBlastLeft
	global.__objectDepths[219] = 0; // oShotgunBlastRight
	global.__objectDepths[220] = 0; // oBullet
	global.__objectDepths[221] = 0; // oFly
	global.__objectDepths[222] = 1; // oLaser
	global.__objectDepths[223] = 1; // oLaserTrail
	global.__objectDepths[224] = 1; // oPsychicWave
	global.__objectDepths[225] = 1; // oPsychicWaveP
	global.__objectDepths[226] = 1; // oPsychicCreate
	global.__objectDepths[227] = 1; // oPsychicCreate2
	global.__objectDepths[228] = 1; // oPsychicCreateP
	global.__objectDepths[229] = 1; // oLaserExplode
	global.__objectDepths[230] = 1; // oYellowBall
	global.__objectDepths[231] = 1; // oYellowTrail
	global.__objectDepths[232] = 150; // oFlareSpark
	global.__objectDepths[233] = 1; // oWebBall
	global.__objectDepths[234] = 200; // oWeb
	global.__objectDepths[235] = 110; // oTrapBlock
	global.__objectDepths[236] = 0; // oArrowTrapTest
	global.__objectDepths[237] = 110; // oArrowTrapRight
	global.__objectDepths[238] = 110; // oArrowTrapRightLit
	global.__objectDepths[239] = 110; // oArrowTrapLeft
	global.__objectDepths[240] = 110; // oArrowTrapLeftLit
	global.__objectDepths[241] = 110; // oArrowRepeaterR
	global.__objectDepths[242] = 110; // oArrowRepeaterL
	global.__objectDepths[243] = 110; // oTemp
	global.__objectDepths[244] = 100; // oSpearTrapTop
	global.__objectDepths[245] = 100; // oSpearTrapLit
	global.__objectDepths[246] = 100; // oSpearTrapBottom
	global.__objectDepths[247] = 999; // oSpearsLeft
	global.__objectDepths[248] = 60; // oThwompTrap
	global.__objectDepths[249] = 60; // oSmashTrap
	global.__objectDepths[250] = 60; // oSmashTrapLit
	global.__objectDepths[251] = 60; // oCeilingTrap
	global.__objectDepths[252] = 9000; // oDoor
	global.__objectDepths[253] = 120; // oSpikes
	global.__objectDepths[254] = 997; // oGiantTikiHead
	global.__objectDepths[255] = 100; // oSpringTrap
	global.__objectDepths[256] = 200; // oBoulder
	global.__objectDepths[257] = 999; // oButtonHighscore
	global.__objectDepths[258] = 999999; // oTitleBG
	global.__objectDepths[259] = 1; // oTitleLogo
	global.__objectDepths[260] = 999999; // oXStart
	global.__objectDepths[261] = 999999; // oXTutorial
	global.__objectDepths[262] = 999999; // oXScores
	global.__objectDepths[263] = 999999; // oXTitle
	global.__objectDepths[264] = 9000; // oXEnd
	global.__objectDepths[265] = 999999; // oXShortcut5
	global.__objectDepths[266] = 999999; // oXShortcut9
	global.__objectDepths[267] = 999999; // oXShortcut13
	global.__objectDepths[268] = 999999; // oXSun
	global.__objectDepths[269] = 999999; // oXMoon
	global.__objectDepths[270] = 999999; // oXStars
	global.__objectDepths[271] = 999999; // oXChange
	global.__objectDepths[272] = 999999; // oXChange2
	global.__objectDepths[273] = 999; // oStartSign
	global.__objectDepths[274] = 999; // oScoresSign
	global.__objectDepths[275] = 999; // oLevel5Sign
	global.__objectDepths[276] = 999; // oLevel9Sign
	global.__objectDepths[277] = 999; // oLevel13Sign
	global.__objectDepths[278] = 999; // oResetSign
	global.__objectDepths[279] = 999; // oQuitSign
	global.__objectDepths[280] = 999; // oTutorialSign
	global.__objectDepths[281] = 99; // oBasket
	global.__objectDepths[282] = 99; // oRim
	global.__objectDepths[283] = 99; // oRimDeflect
	global.__objectDepths[284] = 0; // oTarget
	global.__objectDepths[285] = 0; // oBatTarget
	global.__objectDepths[286] = 0; // oNew
	global.__objectDepths[287] = 900; // oTrophy
	global.__objectDepths[288] = 900; // oMultiTrophy
	global.__objectDepths[289] = 0; // oCopy
	global.__objectDepths[290] = 0; // oBatIntro
	global.__objectDepths[291] = 9999; // oIntroBG
	global.__objectDepths[292] = 999; // oPalmTreeDark
	global.__objectDepths[293] = 999; // oPalmTree
	global.__objectDepths[294] = 998; // oShrubDark
	global.__objectDepths[295] = 998; // oShrub
	global.__objectDepths[296] = 200; // oCamel
	global.__objectDepths[297] = 200; // oCaravan
	global.__objectDepths[298] = 99999; // oMoon
	global.__objectDepths[299] = 10; // oDesertTop
	global.__objectDepths[300] = 10; // oDesertTopScroll
	global.__objectDepths[301] = 100; // oDesert
	global.__objectDepths[302] = 100; // oDesert2
	global.__objectDepths[303] = 100; // oDesertScroll
	global.__objectDepths[304] = 100; // oDesertScroll2
	global.__objectDepths[305] = 999; // oPalmTreeScroll
	global.__objectDepths[306] = 998; // oShrubScroll
	global.__objectDepths[307] = 9999; // oEndWall
	global.__objectDepths[308] = 0; // oBigChest
	global.__objectDepths[309] = 997; // oBigTreasure
	global.__objectDepths[310] = 1; // oPlayerSil
	global.__objectDepths[311] = 1; // oTreasureSil
	global.__objectDepths[312] = 999; // oLavaSpray
	global.__objectDepths[313] = 999; // oEndPlat
	global.__objectDepths[314] = 9999; // oEnd2BG
	global.__objectDepths[315] = 9999; // oBGEnd3
	global.__objectDepths[316] = 100; // oWalDamsel
	global.__objectDepths[317] = 0; // oPageUp
	global.__objectDepths[318] = 0; // oPageDown
	global.__objectDepths[319] = 1; // oMenuSel
	global.__objectDepths[320] = 0; // oHintHand
	global.__objectDepths[321] = 1; // oMenuTop
	global.__objectDepths[322] = 1; // oMenuBottom
	global.__objectDepths[323] = 1; // oMenuLeft
	global.__objectDepths[324] = 1; // oMenuRight
	global.__objectDepths[325] = 1; // oMenuUL
	global.__objectDepths[326] = 1; // oMenuUR
	global.__objectDepths[327] = 1; // oMenuLL
	global.__objectDepths[328] = 1; // oMenuLR
	global.__objectDepths[329] = 1; // oBlack
	global.__objectDepths[330] = 9999999; // oBlackBG
	global.__objectDepths[331] = 0; // oCaveUp
	global.__objectDepths[332] = 50; // oPDummy
	global.__objectDepths[333] = 997; // oPDummy2
	global.__objectDepths[334] = 40; // oPDummy3
	global.__objectDepths[335] = 50; // oPDummy4
	global.__objectDepths[336] = 50; // oPDummy5
	global.__objectDepths[337] = 50; // oPDummy6
	global.__objectDepths[338] = 1; // oYellHelp
	global.__objectDepths[339] = 100; // oDamsel
	global.__objectDepths[340] = 100; // oDamselKiss
	global.__objectDepths[341] = 60; // oShopkeeper
	global.__objectDepths[342] = 60; // oShopkeeper2
	global.__objectDepths[343] = 100; // oTunnelMan
	global.__objectDepths[344] = 100; // oIceTile
	global.__objectDepths[345] = 100; // oWebTile
	global.__objectDepths[346] = 100; // oBatTile
	global.__objectDepths[347] = 100; // oSnakeTile
	global.__objectDepths[348] = 100; // oSpiderTile
	global.__objectDepths[349] = 200; // oGiantSpiderTile
	global.__objectDepths[350] = 100; // oCavemanTile
	global.__objectDepths[351] = 100; // oYetiTile
	global.__objectDepths[352] = 200; // oYetiKingTile
	global.__objectDepths[353] = 100; // oHawkmanTile
	global.__objectDepths[354] = 100; // oManTrapTile
	global.__objectDepths[355] = 100; // oSkeletonTile
	global.__objectDepths[356] = 200; // oTombLordTile
	global.__objectDepths[357] = 100; // oMonkeyTile
	global.__objectDepths[358] = 100; // oFrogTile
	global.__objectDepths[359] = 100; // oFireFrogTile
	global.__objectDepths[360] = 100; // oZombieTile
	global.__objectDepths[361] = 100; // oVampireTile
	global.__objectDepths[362] = 100; // oPiranhaTile
	global.__objectDepths[363] = 200; // oMegaMouthTile
	global.__objectDepths[364] = 100; // oAlienTile
	global.__objectDepths[365] = 100; // oUFOTile
	global.__objectDepths[366] = 200; // oAlienBossTile
	global.__objectDepths[367] = 100; // oShopkeeperTile
	global.__objectDepths[368] = 100; // oBonesTile
	global.__objectDepths[369] = 100; // oSmashTrapTile
	global.__objectDepths[370] = 100; // oSpringTrapTile
	global.__objectDepths[371] = 100; // oSpearTrapTileTop
	global.__objectDepths[372] = 100; // oSpearTrapTileBot
	global.__objectDepths[373] = 100; // oGoldBarTile
	global.__objectDepths[374] = 100; // oGoldBarsTile
	global.__objectDepths[375] = 100; // oGoldIdolTile
	global.__objectDepths[376] = 100; // oCrystalSkullTile
	global.__objectDepths[377] = 100; // oEmeraldBigTile
	global.__objectDepths[378] = 100; // oSapphireBigTile
	global.__objectDepths[379] = 100; // oRubyBigTile
	global.__objectDepths[380] = 100; // oDiamondTile
	global.__objectDepths[381] = 100; // oRockTile
	global.__objectDepths[382] = 100; // oJarTile
	global.__objectDepths[383] = 100; // oChestTile
	global.__objectDepths[384] = 100; // oCrateTile
	global.__objectDepths[385] = 100; // oBombBagTile
	global.__objectDepths[386] = 100; // oBombBoxTile
	global.__objectDepths[387] = 100; // oBombPasteTile
	global.__objectDepths[388] = 100; // oRopePileTile
	global.__objectDepths[389] = 100; // oSpectaclesTile
	global.__objectDepths[390] = 100; // oGlovesTile
	global.__objectDepths[391] = 100; // oCapeTile
	global.__objectDepths[392] = 100; // oSpringShoesTile
	global.__objectDepths[393] = 100; // oSpikeShoesTile
	global.__objectDepths[394] = 100; // oMittTile
	global.__objectDepths[395] = 100; // oParachuteTile
	global.__objectDepths[396] = 100; // oMacheteTile
	global.__objectDepths[397] = 100; // oMattockTile
	global.__objectDepths[398] = 100; // oPistolTile
	global.__objectDepths[399] = 100; // oShotgunTile
	global.__objectDepths[400] = 100; // oWebCannonTile
	global.__objectDepths[401] = 100; // oTeleporterTile
	global.__objectDepths[402] = 100; // oBowTile
	global.__objectDepths[403] = 100; // oCompassTile
	global.__objectDepths[404] = 100; // oJetpackTile
	global.__objectDepths[405] = 100; // oDamselTile
	global.__objectDepths[406] = 999; // oWaterTile
	global.__objectDepths[407] = 100; // oLavaTile
	global.__objectDepths[408] = 0; // oEditButton
	global.__objectDepths[409] = 0; // oTestButton
	global.__objectDepths[410] = 0; // oNewButton
	global.__objectDepths[411] = 1; // oLoadButton
	global.__objectDepths[412] = 0; // oRadioBox
	global.__objectDepths[413] = 0; // oCheckBox
	global.__objectDepths[414] = 0; // oCheckBox2
	global.__objectDepths[415] = 0; // oCheckBox3
	global.__objectDepths[416] = 0; // oCheckBox4
	global.__objectDepths[417] = 0; // oSlider1
	global.__objectDepths[418] = 0; // oSlider2
	global.__objectDepths[419] = 0; // oSliderBG
	global.__objectDepths[420] = 0; // oKeyConfigButton
	global.__objectDepths[421] = 0; // oJoyConfigButton
	global.__objectDepths[422] = 0; // oGameMakerLogo
	global.__objectDepths[423] = -2; // oGameMakerLogoMadeWith
	global.__objectDepths[424] = 2; // oGameMakerLogoPoof
	global.__objectDepths[425] = 0; // oGamepad
	global.__objectDepths[426] = 0; // oKeyConfig
	global.__objectDepths[427] = 0; // oJoyConfig
	global.__objectDepths[428] = 0; // oJoyConfigHtml5
	global.__objectDepths[429] = 0; // oScreen
	global.__objectDepths[430] = 999999; // oScreenFirst
	global.__objectDepths[431] = -999999; // oScreenLast
	global.__objectDepths[432] = 0; // oGlobals
	global.__objectDepths[433] = 0; // oGame
	global.__objectDepths[434] = 0; // oHighscores
	global.__objectDepths[435] = 0; // oSunRoom
	global.__objectDepths[436] = 0; // oMoonRoom
	global.__objectDepths[437] = 0; // oStarsRoom
	global.__objectDepths[438] = -2; // oLevel
	global.__objectDepths[439] = 1; // oLevelEditor
	global.__objectDepths[440] = 0; // oCursObj
	global.__objectDepths[441] = 0; // oLoadLevel
	global.__objectDepths[442] = 0; // oBricks
	global.__objectDepths[443] = 0; // oTransition
	global.__objectDepths[444] = -99999991; // oSprite
	global.__objectDepths[445] = 0; // oFinalBoss
	global.__objectDepths[446] = 0; // oEnd
	global.__objectDepths[447] = 0; // oEnd2
	global.__objectDepths[448] = 0; // oEnd3
	global.__objectDepths[449] = 0; // oEndCustom
	global.__objectDepths[450] = 0; // oIntro
	global.__objectDepths[451] = 0; // oCredits1
	global.__objectDepths[452] = 0; // oCredits2
	global.__objectDepths[453] = 0; // oTitle
	global.__objectDepths[454] = 50; // oPlayer1
	global.__objectDepths[455] = 0; // oRoom
	global.__objectDepths[456] = 0; // core
	global.__objectDepths[457] = 0; // mascara
	global.__objectDepths[458] = 0; // mascara2
	global.__objectDepths[459] = 0; // oNAL
	global.__objectDepths[460] = 0; // oPressStart
	global.__objectDepths[461] = 0; // yyScreen
	global.__objectDepths[462] = 0; // oDebug
	global.__objectDepths[463] = 0; // oHtml5Gamepad


	global.__objectNames[0] = "oMenu";
	global.__objectNames[1] = "oDrawnSprite";
	global.__objectNames[2] = "oCharacter";
	global.__objectNames[3] = "oEnemy";
	global.__objectNames[4] = "oLadder";
	global.__objectNames[5] = "oMoveableSolid";
	global.__objectNames[6] = "oMovingSolid";
	global.__objectNames[7] = "oPlatform";
	global.__objectNames[8] = "oSolid";
	global.__objectNames[9] = "oBackdrop";
	global.__objectNames[10] = "oForeground";
	global.__objectNames[11] = "oWater";
	global.__objectNames[12] = "oItem";
	global.__objectNames[13] = "oTreasure";
	global.__objectNames[14] = "oDetritus";
	global.__objectNames[15] = "oRubblePiece";
	global.__objectNames[16] = "oFrill";
	global.__objectNames[17] = "oGhost";
	global.__objectNames[18] = "oBat";
	global.__objectNames[19] = "oScarab";
	global.__objectNames[20] = "oSnake";
	global.__objectNames[21] = "oSpider";
	global.__objectNames[22] = "oSpiderHang";
	global.__objectNames[23] = "oGiantSpiderHang";
	global.__objectNames[24] = "oGiantSpider";
	global.__objectNames[25] = "oSkeleton";
	global.__objectNames[26] = "oFrog";
	global.__objectNames[27] = "oFireFrog";
	global.__objectNames[28] = "oZombie";
	global.__objectNames[29] = "oVampire";
	global.__objectNames[30] = "oPiranha";
	global.__objectNames[31] = "oJaws";
	global.__objectNames[32] = "oDeadFish";
	global.__objectNames[33] = "oManTrap";
	global.__objectNames[34] = "oMonkey";
	global.__objectNames[35] = "oYeti";
	global.__objectNames[36] = "oYetiKing";
	global.__objectNames[37] = "oUFO";
	global.__objectNames[38] = "oUFOCrash";
	global.__objectNames[39] = "oAlienEject";
	global.__objectNames[40] = "oAlien";
	global.__objectNames[41] = "oAlienBoss";
	global.__objectNames[42] = "oBarrierEmitter";
	global.__objectNames[43] = "oBarrier";
	global.__objectNames[44] = "oCaveman";
	global.__objectNames[45] = "oHawkman";
	global.__objectNames[46] = "oMagma";
	global.__objectNames[47] = "oMagmaTrail";
	global.__objectNames[48] = "oMagmaMan";
	global.__objectNames[49] = "oTombLord";
	global.__objectNames[50] = "oOlmec";
	global.__objectNames[51] = "oCavemanWorship";
	global.__objectNames[52] = "oHawkmanWorship";
	global.__objectNames[53] = "oOlmecDebris";
	global.__objectNames[54] = "oOlmecSlam";
	global.__objectNames[55] = "oEnemySight";
	global.__objectNames[56] = "oEntranceCheck";
	global.__objectNames[57] = "oRopeThrow";
	global.__objectNames[58] = "oRope";
	global.__objectNames[59] = "oRopeTop";
	global.__objectNames[60] = "oWhip";
	global.__objectNames[61] = "oWhipPre";
	global.__objectNames[62] = "oMachetePre";
	global.__objectNames[63] = "oSlash";
	global.__objectNames[64] = "oMattockPre";
	global.__objectNames[65] = "oMattockHit";
	global.__objectNames[66] = "oBomb";
	global.__objectNames[67] = "oBall";
	global.__objectNames[68] = "oChain";
	global.__objectNames[69] = "oBall2";
	global.__objectNames[70] = "oChain2";
	global.__objectNames[71] = "oFireFrogBomb";
	global.__objectNames[72] = "oRock";
	global.__objectNames[73] = "oDice";
	global.__objectNames[74] = "oMattockHead";
	global.__objectNames[75] = "oBasketball";
	global.__objectNames[76] = "oShotgun";
	global.__objectNames[77] = "oPistol";
	global.__objectNames[78] = "oWebCannon";
	global.__objectNames[79] = "oTeleporter";
	global.__objectNames[80] = "oBow";
	global.__objectNames[81] = "oMachete";
	global.__objectNames[82] = "oSceptre";
	global.__objectNames[83] = "oMattock";
	global.__objectNames[84] = "oJar";
	global.__objectNames[85] = "oSkull";
	global.__objectNames[86] = "oArrow";
	global.__objectNames[87] = "oFishBone";
	global.__objectNames[88] = "oFlare";
	global.__objectNames[89] = "oGoldIdol";
	global.__objectNames[90] = "oCrystalSkull";
	global.__objectNames[91] = "oLampItem";
	global.__objectNames[92] = "oLampRedItem";
	global.__objectNames[93] = "oParachute";
	global.__objectNames[94] = "oCaveBG";
	global.__objectNames[95] = "oCaveBG2";
	global.__objectNames[96] = "oCaveBGEntrance";
	global.__objectNames[97] = "oEntrance";
	global.__objectNames[98] = "oGoldDoor";
	global.__objectNames[99] = "oExit";
	global.__objectNames[100] = "oXMarket";
	global.__objectNames[101] = "oXGold";
	global.__objectNames[102] = "oMsgSign";
	global.__objectNames[103] = "oBrick";
	global.__objectNames[104] = "oBrickSmooth";
	global.__objectNames[105] = "oSign";
	global.__objectNames[106] = "oLamp";
	global.__objectNames[107] = "oLampRed";
	global.__objectNames[108] = "oLush";
	global.__objectNames[109] = "oTikiTorch";
	global.__objectNames[110] = "oTree";
	global.__objectNames[111] = "oTreeTile";
	global.__objectNames[112] = "oLeaves";
	global.__objectNames[113] = "oLeavesTile";
	global.__objectNames[114] = "oTreeBranch";
	global.__objectNames[115] = "oTreeBranchTile";
	global.__objectNames[116] = "oDark";
	global.__objectNames[117] = "oDarkFall";
	global.__objectNames[118] = "oAlienShip";
	global.__objectNames[119] = "oAlienShipFloor";
	global.__objectNames[120] = "oMoai";
	global.__objectNames[121] = "oMoai2";
	global.__objectNames[122] = "oMoai3";
	global.__objectNames[123] = "oMoaiInside";
	global.__objectNames[124] = "oTemple";
	global.__objectNames[125] = "oTempleFake";
	global.__objectNames[126] = "oGold";
	global.__objectNames[127] = "oGoldBig";
	global.__objectNames[128] = "oBlock";
	global.__objectNames[129] = "oXocBlock";
	global.__objectNames[130] = "oGrave";
	global.__objectNames[131] = "oAltarLeft";
	global.__objectNames[132] = "oAltarRight";
	global.__objectNames[133] = "oSacAltarLeft";
	global.__objectNames[134] = "oSacAltarRight";
	global.__objectNames[135] = "oKaliHead";
	global.__objectNames[136] = "oLavaSolid";
	global.__objectNames[137] = "oPushBlock";
	global.__objectNames[138] = "oIceBlock";
	global.__objectNames[139] = "oIce";
	global.__objectNames[140] = "oIceBottom";
	global.__objectNames[141] = "oThinIce";
	global.__objectNames[142] = "oFrozenCaveman";
	global.__objectNames[143] = "oSplash";
	global.__objectNames[144] = "oWaterSwim";
	global.__objectNames[145] = "oLava";
	global.__objectNames[146] = "oLadderOrange";
	global.__objectNames[147] = "oLadderTop";
	global.__objectNames[148] = "oVine";
	global.__objectNames[149] = "oVineTop";
	global.__objectNames[150] = "oHardBlock";
	global.__objectNames[151] = "oBlackFadeUp";
	global.__objectNames[152] = "oCaveLeft";
	global.__objectNames[153] = "oCaveRight";
	global.__objectNames[154] = "oFakeBones";
	global.__objectNames[155] = "oBones";
	global.__objectNames[156] = "oParaUsed";
	global.__objectNames[157] = "oChest";
	global.__objectNames[158] = "oLockedChest";
	global.__objectNames[159] = "oKey";
	global.__objectNames[160] = "oCrate";
	global.__objectNames[161] = "oFlareCrate";
	global.__objectNames[162] = "oFireFrogArmed";
	global.__objectNames[163] = "oBombBag";
	global.__objectNames[164] = "oBombBox";
	global.__objectNames[165] = "oPaste";
	global.__objectNames[166] = "oRopePile";
	global.__objectNames[167] = "oParaPickup";
	global.__objectNames[168] = "oCompass";
	global.__objectNames[169] = "oSpringShoes";
	global.__objectNames[170] = "oSpikeShoes";
	global.__objectNames[171] = "oJordans";
	global.__objectNames[172] = "oSpectacles";
	global.__objectNames[173] = "oUdjatEye";
	global.__objectNames[174] = "oCrown";
	global.__objectNames[175] = "oKapala";
	global.__objectNames[176] = "oAnkh";
	global.__objectNames[177] = "oGloves";
	global.__objectNames[178] = "oMitt";
	global.__objectNames[179] = "oJetpack";
	global.__objectNames[180] = "oCapePickup";
	global.__objectNames[181] = "oCape";
	global.__objectNames[182] = "oRopeBag";
	global.__objectNames[183] = "oGoldChunk";
	global.__objectNames[184] = "oGoldNugget";
	global.__objectNames[185] = "oGoldBar";
	global.__objectNames[186] = "oGoldBars";
	global.__objectNames[187] = "oEmerald";
	global.__objectNames[188] = "oEmeraldBig";
	global.__objectNames[189] = "oSapphire";
	global.__objectNames[190] = "oSapphireBig";
	global.__objectNames[191] = "oRuby";
	global.__objectNames[192] = "oRubyBig";
	global.__objectNames[193] = "oDiamond";
	global.__objectNames[194] = "oSmallCollect";
	global.__objectNames[195] = "oBigCollect";
	global.__objectNames[196] = "oHeart";
	global.__objectNames[197] = "oItemsGet";
	global.__objectNames[198] = "oBlood";
	global.__objectNames[199] = "oBloodTrail";
	global.__objectNames[200] = "oBloodSpark";
	global.__objectNames[201] = "oDrip";
	global.__objectNames[202] = "oLavaDrip";
	global.__objectNames[203] = "oLeaf";
	global.__objectNames[204] = "oRubble";
	global.__objectNames[205] = "oRubbleSmall";
	global.__objectNames[206] = "oRubbleDark";
	global.__objectNames[207] = "oRubbleDarkSmall";
	global.__objectNames[208] = "oBubble";
	global.__objectNames[209] = "oSmokePuff";
	global.__objectNames[210] = "oPoof";
	global.__objectNames[211] = "oBone";
	global.__objectNames[212] = "oBurn";
	global.__objectNames[213] = "oRopeBurn";
	global.__objectNames[214] = "oFlame";
	global.__objectNames[215] = "oFlameTrail";
	global.__objectNames[216] = "oVolcanoFlame";
	global.__objectNames[217] = "oExplosion";
	global.__objectNames[218] = "oShotgunBlastLeft";
	global.__objectNames[219] = "oShotgunBlastRight";
	global.__objectNames[220] = "oBullet";
	global.__objectNames[221] = "oFly";
	global.__objectNames[222] = "oLaser";
	global.__objectNames[223] = "oLaserTrail";
	global.__objectNames[224] = "oPsychicWave";
	global.__objectNames[225] = "oPsychicWaveP";
	global.__objectNames[226] = "oPsychicCreate";
	global.__objectNames[227] = "oPsychicCreate2";
	global.__objectNames[228] = "oPsychicCreateP";
	global.__objectNames[229] = "oLaserExplode";
	global.__objectNames[230] = "oYellowBall";
	global.__objectNames[231] = "oYellowTrail";
	global.__objectNames[232] = "oFlareSpark";
	global.__objectNames[233] = "oWebBall";
	global.__objectNames[234] = "oWeb";
	global.__objectNames[235] = "oTrapBlock";
	global.__objectNames[236] = "oArrowTrapTest";
	global.__objectNames[237] = "oArrowTrapRight";
	global.__objectNames[238] = "oArrowTrapRightLit";
	global.__objectNames[239] = "oArrowTrapLeft";
	global.__objectNames[240] = "oArrowTrapLeftLit";
	global.__objectNames[241] = "oArrowRepeaterR";
	global.__objectNames[242] = "oArrowRepeaterL";
	global.__objectNames[243] = "oTemp";
	global.__objectNames[244] = "oSpearTrapTop";
	global.__objectNames[245] = "oSpearTrapLit";
	global.__objectNames[246] = "oSpearTrapBottom";
	global.__objectNames[247] = "oSpearsLeft";
	global.__objectNames[248] = "oThwompTrap";
	global.__objectNames[249] = "oSmashTrap";
	global.__objectNames[250] = "oSmashTrapLit";
	global.__objectNames[251] = "oCeilingTrap";
	global.__objectNames[252] = "oDoor";
	global.__objectNames[253] = "oSpikes";
	global.__objectNames[254] = "oGiantTikiHead";
	global.__objectNames[255] = "oSpringTrap";
	global.__objectNames[256] = "oBoulder";
	global.__objectNames[257] = "oButtonHighscore";
	global.__objectNames[258] = "oTitleBG";
	global.__objectNames[259] = "oTitleLogo";
	global.__objectNames[260] = "oXStart";
	global.__objectNames[261] = "oXTutorial";
	global.__objectNames[262] = "oXScores";
	global.__objectNames[263] = "oXTitle";
	global.__objectNames[264] = "oXEnd";
	global.__objectNames[265] = "oXShortcut5";
	global.__objectNames[266] = "oXShortcut9";
	global.__objectNames[267] = "oXShortcut13";
	global.__objectNames[268] = "oXSun";
	global.__objectNames[269] = "oXMoon";
	global.__objectNames[270] = "oXStars";
	global.__objectNames[271] = "oXChange";
	global.__objectNames[272] = "oXChange2";
	global.__objectNames[273] = "oStartSign";
	global.__objectNames[274] = "oScoresSign";
	global.__objectNames[275] = "oLevel5Sign";
	global.__objectNames[276] = "oLevel9Sign";
	global.__objectNames[277] = "oLevel13Sign";
	global.__objectNames[278] = "oResetSign";
	global.__objectNames[279] = "oQuitSign";
	global.__objectNames[280] = "oTutorialSign";
	global.__objectNames[281] = "oBasket";
	global.__objectNames[282] = "oRim";
	global.__objectNames[283] = "oRimDeflect";
	global.__objectNames[284] = "oTarget";
	global.__objectNames[285] = "oBatTarget";
	global.__objectNames[286] = "oNew";
	global.__objectNames[287] = "oTrophy";
	global.__objectNames[288] = "oMultiTrophy";
	global.__objectNames[289] = "oCopy";
	global.__objectNames[290] = "oBatIntro";
	global.__objectNames[291] = "oIntroBG";
	global.__objectNames[292] = "oPalmTreeDark";
	global.__objectNames[293] = "oPalmTree";
	global.__objectNames[294] = "oShrubDark";
	global.__objectNames[295] = "oShrub";
	global.__objectNames[296] = "oCamel";
	global.__objectNames[297] = "oCaravan";
	global.__objectNames[298] = "oMoon";
	global.__objectNames[299] = "oDesertTop";
	global.__objectNames[300] = "oDesertTopScroll";
	global.__objectNames[301] = "oDesert";
	global.__objectNames[302] = "oDesert2";
	global.__objectNames[303] = "oDesertScroll";
	global.__objectNames[304] = "oDesertScroll2";
	global.__objectNames[305] = "oPalmTreeScroll";
	global.__objectNames[306] = "oShrubScroll";
	global.__objectNames[307] = "oEndWall";
	global.__objectNames[308] = "oBigChest";
	global.__objectNames[309] = "oBigTreasure";
	global.__objectNames[310] = "oPlayerSil";
	global.__objectNames[311] = "oTreasureSil";
	global.__objectNames[312] = "oLavaSpray";
	global.__objectNames[313] = "oEndPlat";
	global.__objectNames[314] = "oEnd2BG";
	global.__objectNames[315] = "oBGEnd3";
	global.__objectNames[316] = "oWalDamsel";
	global.__objectNames[317] = "oPageUp";
	global.__objectNames[318] = "oPageDown";
	global.__objectNames[319] = "oMenuSel";
	global.__objectNames[320] = "oHintHand";
	global.__objectNames[321] = "oMenuTop";
	global.__objectNames[322] = "oMenuBottom";
	global.__objectNames[323] = "oMenuLeft";
	global.__objectNames[324] = "oMenuRight";
	global.__objectNames[325] = "oMenuUL";
	global.__objectNames[326] = "oMenuUR";
	global.__objectNames[327] = "oMenuLL";
	global.__objectNames[328] = "oMenuLR";
	global.__objectNames[329] = "oBlack";
	global.__objectNames[330] = "oBlackBG";
	global.__objectNames[331] = "oCaveUp";
	global.__objectNames[332] = "oPDummy";
	global.__objectNames[333] = "oPDummy2";
	global.__objectNames[334] = "oPDummy3";
	global.__objectNames[335] = "oPDummy4";
	global.__objectNames[336] = "oPDummy5";
	global.__objectNames[337] = "oPDummy6";
	global.__objectNames[338] = "oYellHelp";
	global.__objectNames[339] = "oDamsel";
	global.__objectNames[340] = "oDamselKiss";
	global.__objectNames[341] = "oShopkeeper";
	global.__objectNames[342] = "oShopkeeper2";
	global.__objectNames[343] = "oTunnelMan";
	global.__objectNames[344] = "oIceTile";
	global.__objectNames[345] = "oWebTile";
	global.__objectNames[346] = "oBatTile";
	global.__objectNames[347] = "oSnakeTile";
	global.__objectNames[348] = "oSpiderTile";
	global.__objectNames[349] = "oGiantSpiderTile";
	global.__objectNames[350] = "oCavemanTile";
	global.__objectNames[351] = "oYetiTile";
	global.__objectNames[352] = "oYetiKingTile";
	global.__objectNames[353] = "oHawkmanTile";
	global.__objectNames[354] = "oManTrapTile";
	global.__objectNames[355] = "oSkeletonTile";
	global.__objectNames[356] = "oTombLordTile";
	global.__objectNames[357] = "oMonkeyTile";
	global.__objectNames[358] = "oFrogTile";
	global.__objectNames[359] = "oFireFrogTile";
	global.__objectNames[360] = "oZombieTile";
	global.__objectNames[361] = "oVampireTile";
	global.__objectNames[362] = "oPiranhaTile";
	global.__objectNames[363] = "oMegaMouthTile";
	global.__objectNames[364] = "oAlienTile";
	global.__objectNames[365] = "oUFOTile";
	global.__objectNames[366] = "oAlienBossTile";
	global.__objectNames[367] = "oShopkeeperTile";
	global.__objectNames[368] = "oBonesTile";
	global.__objectNames[369] = "oSmashTrapTile";
	global.__objectNames[370] = "oSpringTrapTile";
	global.__objectNames[371] = "oSpearTrapTileTop";
	global.__objectNames[372] = "oSpearTrapTileBot";
	global.__objectNames[373] = "oGoldBarTile";
	global.__objectNames[374] = "oGoldBarsTile";
	global.__objectNames[375] = "oGoldIdolTile";
	global.__objectNames[376] = "oCrystalSkullTile";
	global.__objectNames[377] = "oEmeraldBigTile";
	global.__objectNames[378] = "oSapphireBigTile";
	global.__objectNames[379] = "oRubyBigTile";
	global.__objectNames[380] = "oDiamondTile";
	global.__objectNames[381] = "oRockTile";
	global.__objectNames[382] = "oJarTile";
	global.__objectNames[383] = "oChestTile";
	global.__objectNames[384] = "oCrateTile";
	global.__objectNames[385] = "oBombBagTile";
	global.__objectNames[386] = "oBombBoxTile";
	global.__objectNames[387] = "oBombPasteTile";
	global.__objectNames[388] = "oRopePileTile";
	global.__objectNames[389] = "oSpectaclesTile";
	global.__objectNames[390] = "oGlovesTile";
	global.__objectNames[391] = "oCapeTile";
	global.__objectNames[392] = "oSpringShoesTile";
	global.__objectNames[393] = "oSpikeShoesTile";
	global.__objectNames[394] = "oMittTile";
	global.__objectNames[395] = "oParachuteTile";
	global.__objectNames[396] = "oMacheteTile";
	global.__objectNames[397] = "oMattockTile";
	global.__objectNames[398] = "oPistolTile";
	global.__objectNames[399] = "oShotgunTile";
	global.__objectNames[400] = "oWebCannonTile";
	global.__objectNames[401] = "oTeleporterTile";
	global.__objectNames[402] = "oBowTile";
	global.__objectNames[403] = "oCompassTile";
	global.__objectNames[404] = "oJetpackTile";
	global.__objectNames[405] = "oDamselTile";
	global.__objectNames[406] = "oWaterTile";
	global.__objectNames[407] = "oLavaTile";
	global.__objectNames[408] = "oEditButton";
	global.__objectNames[409] = "oTestButton";
	global.__objectNames[410] = "oNewButton";
	global.__objectNames[411] = "oLoadButton";
	global.__objectNames[412] = "oRadioBox";
	global.__objectNames[413] = "oCheckBox";
	global.__objectNames[414] = "oCheckBox2";
	global.__objectNames[415] = "oCheckBox3";
	global.__objectNames[416] = "oCheckBox4";
	global.__objectNames[417] = "oSlider1";
	global.__objectNames[418] = "oSlider2";
	global.__objectNames[419] = "oSliderBG";
	global.__objectNames[420] = "oKeyConfigButton";
	global.__objectNames[421] = "oJoyConfigButton";
	global.__objectNames[422] = "oGameMakerLogo";
	global.__objectNames[423] = "oGameMakerLogoMadeWith";
	global.__objectNames[424] = "oGameMakerLogoPoof";
	global.__objectNames[425] = "oGamepad";
	global.__objectNames[426] = "oKeyConfig";
	global.__objectNames[427] = "oJoyConfig";
	global.__objectNames[428] = "oJoyConfigHtml5";
	global.__objectNames[429] = "oScreen";
	global.__objectNames[430] = "oScreenFirst";
	global.__objectNames[431] = "oScreenLast";
	global.__objectNames[432] = "oGlobals";
	global.__objectNames[433] = "oGame";
	global.__objectNames[434] = "oHighscores";
	global.__objectNames[435] = "oSunRoom";
	global.__objectNames[436] = "oMoonRoom";
	global.__objectNames[437] = "oStarsRoom";
	global.__objectNames[438] = "oLevel";
	global.__objectNames[439] = "oLevelEditor";
	global.__objectNames[440] = "oCursObj";
	global.__objectNames[441] = "oLoadLevel";
	global.__objectNames[442] = "oBricks";
	global.__objectNames[443] = "oTransition";
	global.__objectNames[444] = "oSprite";
	global.__objectNames[445] = "oFinalBoss";
	global.__objectNames[446] = "oEnd";
	global.__objectNames[447] = "oEnd2";
	global.__objectNames[448] = "oEnd3";
	global.__objectNames[449] = "oEndCustom";
	global.__objectNames[450] = "oIntro";
	global.__objectNames[451] = "oCredits1";
	global.__objectNames[452] = "oCredits2";
	global.__objectNames[453] = "oTitle";
	global.__objectNames[454] = "oPlayer1";
	global.__objectNames[455] = "oRoom";
	global.__objectNames[456] = "core";
	global.__objectNames[457] = "mascara";
	global.__objectNames[458] = "mascara2";
	global.__objectNames[459] = "oNAL";
	global.__objectNames[460] = "oPressStart";
	global.__objectNames[461] = "yyScreen";
	global.__objectNames[462] = "oDebug";
	global.__objectNames[463] = "oHtml5Gamepad";


	// create another array that has the correct entries
	var len = array_length_1d(global.__objectDepths);
	global.__objectID2Depth = [];
	for( var i=0; i<len; ++i ) {
		var objID = asset_get_index( global.__objectNames[i] );
		if (objID >= 0) {
			global.__objectID2Depth[ objID ] = global.__objectDepths[i];
		} // end if
	} // end for


}
