//
// scrInit()
//
// Initialize the game (mostly controls and audio).
//

/**********************************************************************************
    Copyright (c) 2008, 2009 Derek Yu and Mossmouth, LLC
    
    This file is part of Spelunky.

    You can redistribute and/or modify Spelunky, including its source code, under
    the terms of the Spelunky User License.

    Spelunky is distributed in the hope that it will be entertaining and useful,
    but WITHOUT WARRANTY.  Please see the Spelunky User License for more details.

    The Spelunky User License should be available in "Game Information", which
    can be found in the Resource Explorer, or as an external file called COPYING.
    If not, please obtain a new copy of Spelunky from <http://spelunkyworld.com/>
    
***********************************************************************************/

initMusic()

global.mobileBuild = false;
global.touchControlsVisible = 1;
global.lang = "En";

startGame = false;
window_set_cursor(cr_none);

global.fullscreen = true;
global.graphicsHigh = true;
global.downToRun = true;
global.gamepadOn = false;
global.screenScale = 1;
global.musicVol = 15;
global.soundVol = 15;

global.keyUpVal = vk_up;
global.keyDownVal = vk_down;
global.keyLeftVal = vk_left;
global.keyRightVal = vk_right;
global.keyJumpVal = ord('Z');
global.keyAttackVal = ord('X');
global.keyItemVal = ord('C');
global.keyRunVal = vk_shift;
global.keyBombVal = ord('A');
global.keyRopeVal = ord('S');
global.keyFlareVal = ord('F');
global.keyPayVal = ord('P');

global.joyJumpVal = 2;
global.joyAttackVal = 1;
global.joyItemVal = 3;
global.joyRunVal = 5;
global.joyBombVal = 7;
global.joyRopeVal = 8;
global.joyFlareVal = 4;
global.joyPayVal = 6;
global.joyStartVal = 10;

file = file_text_open_read(working_directory + "settings.cfg");

if (file)
{
    str = file_text_read_string(file);
    if (str == "0") global.fullscreen = false;
    file_text_readln(file);
    str = file_text_read_string(file);
    if (str == "0") global.graphicsHigh = false;
    file_text_readln(file);
    str = file_text_read_string(file);
    if (str == "0") global.downToRun = false;
    file_text_readln(file);
    str = file_text_read_string(file);
    if (str == "0") global.gamepadOn = false;
    else global.gamepadOn = true;
    file_text_readln(file);
    global.screenScale = real(file_text_read_string(file));
    global.screenScale = 1;
    file_text_readln(file);
    global.musicVol = real(file_text_read_string(file));
    file_text_readln(file);
    global.soundVol = real(file_text_read_string(file));
    
    if (global.mobileBuild == false)
    {
        file_text_readln(file);
        global.lang = file_text_read_string(file);
    }
    
    file_text_close(file);
}

if (global.musicVol > 17) global.musicVol = 17;
if (global.musicVol < 0) global.musicVol = 0;
if (global.soundVol > 17) global.soundVol = 17;
if (global.soundVol < 0) global.soundVol = 0;

file = file_text_open_read(working_directory + "keys.cfg");
if (file)
{
    global.keyUpVal = real(file_text_read_string(file));
    file_text_readln(file);
    global.keyDownVal = real(file_text_read_string(file));
    file_text_readln(file);
    global.keyLeftVal = real(file_text_read_string(file));
    file_text_readln(file);
    global.keyRightVal = real(file_text_read_string(file));
    file_text_readln(file);
    global.keyJumpVal = real(file_text_read_string(file));
    file_text_readln(file);
    global.keyAttackVal = real(file_text_read_string(file));
    file_text_readln(file);
    global.keyItemVal = real(file_text_read_string(file));
    file_text_readln(file);
    global.keyRunVal = real(file_text_read_string(file));
    file_text_readln(file);
    global.keyBombVal = real(file_text_read_string(file));
    file_text_readln(file);
    global.keyRopeVal = real(file_text_read_string(file));
    file_text_readln(file);
    global.keyFlareVal = real(file_text_read_string(file));
    file_text_readln(file);
    global.keyPayVal = real(file_text_read_string(file));
    file_text_close(file);
}

file = file_text_open_read(working_directory + "gamepad.cfg");
if (file)
{
    global.joyJumpVal = real(file_text_read_string(file));
    file_text_readln(file);
    global.joyAttackVal = real(file_text_read_string(file));
    file_text_readln(file);
    global.joyItemVal = real(file_text_read_string(file));
    file_text_readln(file);
    global.joyRunVal = real(file_text_read_string(file));
    file_text_readln(file);
    global.joyBombVal = real(file_text_read_string(file));
    file_text_readln(file);
    global.joyRopeVal = real(file_text_read_string(file));
    file_text_readln(file);
    global.joyFlareVal = real(file_text_read_string(file));
    file_text_readln(file);
    global.joyPayVal = real(file_text_read_string(file));
    file_text_readln(file);
    global.joyStartVal = real(file_text_read_string(file));
    file_text_close(file);
}

SS_SetSoundVol(global.musTitle, 2000 + 8000 * (global.musicVol/18));
SS_SetSoundVol(global.musCave, 2000 + 8000 * (global.musicVol/18));
SS_SetSoundVol(global.musLush, 2000 + 8000 * (global.musicVol/18));
SS_SetSoundVol(global.musIce, 2000 + 8000 * (global.musicVol/18));
SS_SetSoundVol(global.musTemple, 2000 + 8000 * (global.musicVol/18));
SS_SetSoundVol(global.musBoss, 2000 + 8000 * (global.musicVol/18));
SS_SetSoundVol(global.musVictory, 2000 + 8000 * (global.musicVol/18));
SS_SetSoundVol(global.musCredits, 2000 + 8000 * (global.musicVol/18));

SS_SetSoundVol(global.sndIgnite, 2000 + 8000 * (global.soundVol/18));
SS_SetSoundVol(global.sndTeleport, 2000 + 8000 * (global.soundVol/18));
SS_SetSoundVol(global.sndJetpack, 2000 + 8000 * (global.soundVol/18));
SS_SetSoundVol(global.sndWhip, 2000 + 8000 * (global.soundVol/18));
SS_SetSoundVol(global.sndJump, 2000 + 8000 * (global.soundVol/18));
SS_SetSoundVol(global.sndThrow, 2000 + 8000 * (global.soundVol/18));
SS_SetSoundVol(global.sndClimb1, 2000 + 8000 * (global.soundVol/18));
SS_SetSoundVol(global.sndClimb2, 2000 + 8000 * (global.soundVol/18));
SS_SetSoundVol(global.sndShotgun, 2000 + 8000 * (global.soundVol/18));
SS_SetSoundVol(global.sndBowPull, 2000 + 8000 * (global.soundVol/18));
SS_SetSoundVol(global.sndSteps, 2000 + 8000 * (global.soundVol/18));
SS_SetSoundVol(global.sndBlink1, 2000 + 8000 * (global.soundVol/18));
SS_SetSoundVol(global.sndBlink2, 2000 + 8000 * (global.soundVol/18));
SS_SetSoundVol(global.sndHit, 2000 + 8000 * (global.soundVol/18));
SS_SetSoundVol(global.sndHurt, 2000 + 8000 * (global.soundVol/18));
SS_SetSoundVol(global.sndDie, 2000 + 8000 * (global.soundVol/18));
SS_SetSoundVol(global.sndCoin, 2000 + 8000 * (global.soundVol/18));
SS_SetSoundVol(global.sndGem, 2000 + 8000 * (global.soundVol/18));
SS_SetSoundVol(global.sndPickup, 2000 + 8000 * (global.soundVol/18));
SS_SetSoundVol(global.sndChestOpen, 2000 + 8000 * (global.soundVol/18));
SS_SetSoundVol(global.sndPush, 2000 + 8000 * (global.soundVol/18));
SS_SetSoundVol(global.sndMattockBreak, 2000 + 8000 * (global.soundVol/18));
SS_SetSoundVol(global.sndTrap, 2000 + 8000 * (global.soundVol/18));
SS_SetSoundVol(global.sndClick, 2000 + 8000 * (global.soundVol/18));
SS_SetSoundVol(global.sndBreak, 2000 + 8000 * (global.soundVol/18));
SS_SetSoundVol(global.sndThud, 2000 + 8000 * (global.soundVol/18));
SS_SetSoundVol(global.sndThump, 2000 + 8000 * (global.soundVol/18));
SS_SetSoundVol(global.sndCrunch, 2000 + 8000 * (global.soundVol/18));
SS_SetSoundVol(global.sndSplash, 2000 + 8000 * (global.soundVol/18));
SS_SetSoundVol(global.sndFlame, 2000 + 8000 * (global.soundVol/18));
SS_SetSoundVol(global.sndExplosion, 2000 + 8000 * (global.soundVol/18));
SS_SetSoundVol(global.sndBoing, 2000 + 8000 * (global.soundVol/18));
SS_SetSoundVol(global.sndArrowTrap, 2000 + 8000 * (global.soundVol/18));
SS_SetSoundVol(global.sndDamsel, 2000 + 8000 * (global.soundVol/18));
SS_SetSoundVol(global.sndKiss, 2000 + 8000 * (global.soundVol/18));
SS_SetSoundVol(global.sndGhost, 2000 + 8000 * (global.soundVol/18));
SS_SetSoundVol(global.sndBat, 2000 + 8000 * (global.soundVol/18));
SS_SetSoundVol(global.sndGiantSpider, 2000 + 8000 * (global.soundVol/18));
SS_SetSoundVol(global.sndSpiderJump, 2000 + 8000 * (global.soundVol/18));
SS_SetSoundVol(global.sndFrog, 2000 + 8000 * (global.soundVol/18));
SS_SetSoundVol(global.sndZombie, 2000 + 8000 * (global.soundVol/18));
SS_SetSoundVol(global.sndMonkey, 2000 + 8000 * (global.soundVol/18));
SS_SetSoundVol(global.sndAlert, 2000 + 8000 * (global.soundVol/18));
SS_SetSoundVol(global.sndCavemanDie, 2000 + 8000 * (global.soundVol/18));
SS_SetSoundVol(global.sndAlien, 2000 + 8000 * (global.soundVol/18));
SS_SetSoundVol(global.sndLaser, 2000 + 8000 * (global.soundVol/18));
SS_SetSoundVol(global.sndLaserCharge, 2000 + 8000 * (global.soundVol/18));
SS_SetSoundVol(global.sndSmallExplode, 2000 + 8000 * (global.soundVol/18));
SS_SetSoundVol(global.sndPsychic, 2000 + 8000 * (global.soundVol/18));
SS_SetSoundVol(global.sndYetiYell, 2000 + 8000 * (global.soundVol/18));
SS_SetSoundVol(global.sndBigJump, 2000 + 8000 * (global.soundVol/18));
SS_SetSoundVol(global.sndSlam, 2000 + 8000 * (global.soundVol/18));
SS_SetSoundVol(global.sndPFall, 2000 + 8000 * (global.soundVol/18));
SS_SetSoundVol(global.sndTFall, 2000 + 8000 * (global.soundVol/18));

if (not joystick_exists(1) and not joystick_exists(2)) global.gamepadOn = false;

globalvar gamepad;
gamepad = instance_create(0, 0, oGamepad);

// if (not joystick_exists(1) and not joystick_exists(2)) global.gamepadOn = false;

/////////////////////////////////////////////////////////////////////////////////
//                              Translations                                   //
/////////////////////////////////////////////////////////////////////////////////

trans_dir = working_directory + "translations/" + global.lang  

if (global.lang == "En")
{
    global.myFont = font_add_sprite(sFont, ord(' '), false, 0);
    global.myFontSmall = font_add_sprite(sFontSmall, ord(' '), false, 0);   
}
else
{   
    file = file_text_open_read(trans_dir + "/charset/charset");
    if (file)
    {
        charset = file_text_read_string(file);
        file_text_close(file);
    }
    
    n_char = string_length(charset);

    Font_lang = sprite_add(trans_dir + "/charset/charset.png", n_char, false, false, 0, 0);
    FontSmall_lang = sprite_add(trans_dir + "/charset/charset_small.png", n_char, false, false, 0, 0);
    
    global.myFont = font_add_sprite_ext(Font_lang, charset, false, 0);
    global.myFontSmall = font_add_sprite_ext(FontSmall_lang, charset, false, 0);
}

/////////////////////////////////////////////////////////////////////////////////

global.DerekYuPresents = "DEREK YU PRESENTS";
global.BetterLuckNextTime = "BETTER LUCK NEXT TIME...";
global.FinalScore = "FINAL SCORE:";
global.ForHighScores = " FOR HIGH SCORES.";
global.GameOver = "GAME OVER";
global.Finished = "FINISHED!";
global.YouSetANewRecord = "YOU SET A NEW RECORD!";
global.Paused = "PAUSED";
global.EcsReturnF1DieF10Quit = "ESC-RETURN  F1-DIE  F10-QUIT";
global.StartReturnBombDieRopeQuit = "START-RETURN  BOMB-DIE  ROPE-QUIT";
global.EscReturnF10Quit = "ESC-RETURN  F10-QUIT";
global.StartReturnRopeQuit = "START-RETURN  ROPE-QUIT";
global.ToEditLevel = " TO EDIT LEVEL.";
global.ToLoadAnotherLevel = " TO LOAD ANOTHER LEVEL.";
global.WelcomeToTheShortcutHouse = "WELCOME TO THE SHORTCUT HOUSE!";
global.Completed = " COMPLETED!";
global.Depth = "DEPTH:";
global.Feet = "FEET";
global.ForANewShortcut = " FOR A NEW SHORTCUT.";
global.Level = "LEVEL ";
global.Kills = "KILLS - ";
global.Loot = "LOOT  - ";
global.Time = "TIME  - ";
global.Money = "MONEY - ";
global.None = "NONE";
global.MyHero = "MY HERO!";
global.OneShortcutComingUp = "ONE SHORTCUT, COMING UP!";
global.IDigShortcuts = "I DIG SHORTCUTS.";
global.Donate = "DONATE:";
global.HeyThereImTheTunnelMan = "HEY THERE! I'M THE TUNNEL MAN!";
global.CanYouLendMeALittleMoney = "CAN YOU LEND ME A LITTLE MONEY?";
global.INeedS = "I NEED $";
global.IllNeverGetThisShortcutBuilt = "I'LL NEVER GET THIS SHORTCUT BUILT!";
global.ThanksYouWontRegretIt = "THANKS! YOU WON'T REGRET IT!";
global.TutorialCaveCompleted = "TUTORIAL CAVE COMPLETED!";
global.SArmory = "'S ARMORY!";
global.SBombShop = "'S BOMB SHOP!";
global.SClothingShop = "'S CLOTHING SHOP!";
global.SDiceHouse = "'S DICE HOUSE!";
global.ImSorryButYouLose = "I'M SORRY, BUT YOU LOSE!";
global.CongratulationsYouWin = "CONGRATULATIONS! YOU WIN!";
global.GetOuttaHereDeadbeat = "GET OUTTA HERE, DEADBEAT!";
global.NowAintHeSweet = "NOW AIN'T HE SWEET!";
global.IHaveSomethingSpecial = "I HAVE SOMETHING SPECIAL...";
global.SKissingParlor = "'S KISSING PARLOR!";
global.AKissPress = " A KISS. PRESS ";
global.YouHaventGotEnoughMoney = "YOU HAVEN'T GOT ENOUGH MONEY!";
global.NowRollTheDice = "NOW ROLL THE DICE!";
global.OneBetAtATime = "ONE BET AT A TIME!";
global.PleaseRollTheDice = "PLEASE ROLL THE DICE!";
global.PleasureDoingBusiness = "PLEASURE DOING BUSINESS!";
global.YouRolledASeven = "YOU ROLLED A SEVEN!";
global.NowAintSheSweet = "NOW AIN'T SHE SWEET!";
global.ComeBackHereThief = "COME BACK HERE, THIEF!";
global.DieYouVandal = "DIE, YOU VANDAL!";
global.Terrorist = "TERRORIST!";
global.HeqOnlyICanDoThat = "HEY, ONLY I CAN DO THAT!";
global.NowImReallySteamed = "NOW I'M REALLY STEAMED!";
global.YoullPayForYourCrimes = "YOU'LL PAY FOR YOUR CRIMES!";
global.SSpecialityShop = "'S SPECIALTY SHOP!";
global.SSupplyShop = "'S SUPPLY SHOP!";
global.ToBetS = " TO BET $";
global.ToPurchase = " TO PURCHASE.";
global.WelcomeTo = "WELCOME TO ";
global.YouWonAPrize = "YOU WIN A PRIZE!";
global.YouBetS = " YOU BET $";
global.YouNeedS = "YOU NEED $";
global.YouRolledA = "YOU ROLLED A ";
global.YouFeelProtected = "YOU FEEL PROTECTED.";
global.YouGotTheAnkh = "YOU GOT THE ANKH!";
global.AnAnkhForS = "AN ANKH FOR $";
global.YouGot3MoreBombs = "YOU GOT 3 MORE BOMBS!";
global.ABagOf3BombsForS = "A BAG OF 3 BOMBS FOR $";
global.YouGot12MoreBombs = "YOU GOT 12 MORE BOMBS!";
global.ABoxOf12BombsForS = "A BOX OF 12 BOMBS FOR $";
global.YouGotTheBowAndArrows = "YOU GOT THE BOW AND ARROWS!";
global.BowAndArrowsForS = "BOW AND ARROWS FOR $";
global.YouGotACape = "YOU GOT A CAPE!";
global.ACapeForS = "A CAPE FOR $";
global.YouGotACompass = "YOU GOT A COMPASS!";
global.ACompassForS = "A COMPASS FOR $";
global.YouGotClimbingGloves = "YOU GOT CLIMBING GLOVES!";
global.ClimbingGlovesForS = "CLIMBING GLOVES FOR $";
global.YourSpiderSenseTingles = "YOUR SPIDER SENSE TINGLES!";
global.ItGlowsABrilliantWhite = "IT GLOWS A BRILLIANT WHITE.";
global.YouGotTheHedjet = "YOU GOT THE HEDJET!";
global.YouGotAJetpack = "YOU GOT A JETPACK!";
global.JetpackForS = "JETPACK FOR $";
global.YouFeelLightOnYourFeet = "YOU FEEL LIGHT ON YOUR FEET.";
global.YouGotJordans = "YOU GOT JORDANS!";
global.JordansForS50000 = "JORDANS FOR $50000!";
global.ItThirstsForBlood = "IT THIRSTS FOR BLOOD...";
global.YouGotTheKapala = "YOU GOT THE KAPALA!";
global.YouGotAMachete = "YOU GOT A MACHETE!";
global.AMacheteForS = "A MACHETE FOR $";
global.ItSeemsABitRusty = "IT SEEMS A BIT RUSTY.";
global.YouGotAMattock = "YOU GOT A MATTOCK!";
global.AMattockForS = "A MATTOCK FOR $";
global.ItWillDeployAutomatically = "IT WILL DEPLOY AUTOMATICALLY.";
global.YouGotAParachute = "YOU GOT A PARACHUTE!";
global.AParachuteForS = "A PARACHUTE FOR $";
global.YouGotStickyBombs = "YOU GOT STICKY BOMBS!";
global.BombPasteForS = "BOMB PASTE FOR $";
global.YouGotAPistol = "YOU GOT A PISTOL!";
global.APistolForS = "A PISTOL FOR $";
global.YouGotAPitcherSMitt = "YOU GOT A PITCHER'S MITT!";
global.PitcherSMittForS = "PITCHER'S MITT FOR $";
global.YouGot3MoreRopes = "YOU GOT 3 MORE ROPES!";
global.ExtraRopeForS = "EXTRA ROPE FOR $";
global.YouGotAShotgun = "YOU GOT A SHOTGUN!";
global.AShotgunForS = "A SHOTGUN FOR $";
global.YourEyesightSeemsImproved = "YOUR EYESIGHT SEEMS IMPROVED...";
global.YouGotSpectacles = "YOU GOT SPECTACLES!";
global.SpectaclesForS = "SPECTACLES FOR $";
global.YouGotSpikeShoes = "YOU GOT SPIKE SHOES!";
global.SpikeShoesForS = "SPIKE SHOES FOR $";
global.YouFeelBouncy = "YOU FEEL BOUNCY.";
global.YouGotSpringShoes = "YOU GOT SPRING SHOES!";
global.SpringyShoesForS = "SPRINGY SHOES FOR $";
global.YouMustBeInLove = "YOU MUST BE IN LOVE!";
global.YouGotATeleporter = "YOU GOT A TELEPORTER!";
global.ATeleporterForS = "A TELEPORTER FOR $";
global.YouFeelAwakened = "YOU FEEL AWAKENED.";
global.YouGotTheUdjatEye = "YOU GOT THE UDJAT EYE!";
global.YouGotAWebCannon = "YOU GOT A WEB CANNON!";
global.AWebCannonForS = "A WEB CANNON FOR $";
global.YouHaveBeenRevived = "YOU HAVE BEEN REVIVED!";
global.TheAnkhShatters = "THE ANKH SHATTERS!";
global.PressEscapeToReturnToTitle = "PRESS ESCAPE TO RETURN TO TITLE.";
global.IMOutOfArrows = "I'M OUT OF ARROWS!";
global.Press = "PRESS ";
global.ButNothingIsHappening = "BUT NOTHING IS HAPPENING!";
global.TheSceptreFits = "THE SCEPTRE FITS...";
global.SheSeemsVeryAngryWithYou = "SHE SEEMS VERY ANGRY WITH YOU!";
global.SheSeemsAngryWithYou = "SHE SEEMS ANGRY WITH YOU.";
global.SheHasForgivenYou = "SHE HAS FORGIVEN YOU!";
global.YouFeelInvigorated = "YOU FEEL INVIGORATED!";
global.SheSeemsEcstaticWithYou = "SHE SEEMS ECSTATIC WITH YOU!";
global.YourSatchelFeelsVeryFullNow = "YOUR SATCHEL FEELS VERY FULL NOW!";
global.SheSeemsVeryHappyWithYou = "SHE SEEMS VERY HAPPY WITH YOU!";
global.SheSeemsHappyWithYou = "SHE SEEMS HAPPY WITH YOU.";
global.SheBestowsAGiftUponYou = "SHE BESTOWS A GIFT UPON YOU!";
global.SheSeemsPleasedWithYou = "SHE SEEMS PLEASED WITH YOU.";
global.KaliAcceptsTheSacrifice = "KALI ACCEPTS THE SACRIFICE!";
global.KaliDevoursTheSacrifice = "KALI DEVOURS THE SACRIFICE!";
global.YouDareDefileMyAltar = "YOU DARE DEFILE MY ALTAR?";
global.IWillPunishYou = "I WILL PUNISH YOU!";
global.AChillRunsUpYourSpine = "A CHILL RUNS UP YOUR SPINE...";
global.LetSGetOutOfHere = "LET'S GET OUT OF HERE!";
global.ThereSAPsychicPresenceHere = "THERE'S A PSYCHIC PRESENCE HERE!";
global.IDBetterUseTheseFlares = "I'D BETTER USE THESE FLARES!";
global.WelcomeToTheBlackMarket = "WELCOME TO THE BLACK MARKET!";
global.ICanTSeeAThing = "I CAN'T SEE A THING!";
global.TheDeadAreRestless = "THE DEAD ARE RESTLESS!";
global.ItSTheLegendaryCityOfGold = "IT'S THE LEGENDARY CITY OF GOLD!";
global.TheHedjetShinesBrightly = "THE HEDJET SHINES BRIGHTLY.";
global.ICanHearRushingWater = "I CAN HEAR RUSHING WATER...";
global.ICanHearPrayersToKali = "I CAN HEAR PRAYERS TO KALI!";
global.IHearSnakesIHateSnakes = "I HEAR SNAKES... I HATE SNAKES!";
global.ItSmellsLikeWetFurInHere = "IT SMELLS LIKE WET FUR IN HERE!";
global.SecretChallenges = "SECRET CHALLENGES";
global.Sun = "SUN:   ";
global.Moon = "MOON:  ";
global.Stars = "STARS: ";
global.SunRoom = "SUN ROOM";
global.KeepYourselfAnd = "KEEP YOURSELF AND";
global.TheDamselAlive = "THE DAMSEL ALIVE";
global.ForAsLongAs = "FOR AS LONG AS";
global.Possible = "POSSIBLE!";
global.DamselChallengeBeginsIn = "DAMSEL CHALLENGE BEGINS IN";
global.Locked = "LOCKED.";
global.MoonRoom = "MOON ROOM";
global.ShootTheMoving = "SHOOT THE MOVING";
global.TargetsWithYour = "TARGETS WITH YOUR";
global.BowAndArrows = "BOW AND ARROWS!";
global.ArcheryChallengeBeginsIn = "ARCHERY CHALLENGE BEGINS IN";
global.StarsRoom = "STARS ROOM";
global.KillAsManyAngry = "KILL AS MANY ANGRY";
global.ShopkeepsAsYouCan = "SHOPKEEPS AS YOU CAN";
global.BeforeTheyGetYou = "BEFORE THEY GET YOU!";
global.ShotgunChallengeBeginsIn = "SHOTGUN CHALLENGE BEGINS IN";
global.ChangingRoom = "CHANGING ROOM";
global.LadyInRed = "LADY IN RED...";
global.TopDefilers = "TOP DEFILERS";
global.Money2 = "MONEY:  ";
global.Kills2 = "KILLS:  ";
global.Saves = "SAVES:  ";
global.Time2 = "TIME:  ";
global.Plays = "PLAYS:  ";
global.Deaths = "DEATHS: ";
global.Wins = "WINS:   ";
global.Statistics = "STATISTICS";
global.ThisWillClearEverything = "THIS WILL CLEAR EVERYTHING!";
global.ToJump = " TO JUMP.";
global.ToUseYourWhip = " TO USE YOUR WHIP.";
global.HoldUpAndPress = "HOLD UP AND PRESS ";
global.WelcomeToTheTutorialCave = "WELCOME TO THE TUTORIAL CAVE!";
global.ThisMightBeYourFirstTimePlaying = "THIS MIGHT BE YOUR FIRST TIME PLAYING.";
global.YouCanHangOnLedgesToo = "YOU CAN HANG ON LEDGES, TOO!";
global.CollectTheTreasure = "COLLECT THE TREASURE!";
global.ToOpenChests = " TO OPEN CHESTS.";
global.HoldDownToDuckAndCrawl = "HOLD DOWN TO DUCK AND CRAWL.";
global.CrawlOverTheEdgeToDoAFlipHang = "CRAWL OVER THE EDGE TO DO A FLIP HANG.";
global.FallingTooFarCanReallyHurt = "FALLING TOO FAR CAN REALLY HURT!";
global.HoldUpToClimbTheLadder = "HOLD UP TO CLIMB THE LADDER.";
global.DuckAndPress = "DUCK AND PRESS ";
global.ToPickUpItems = " TO PICK UP ITEMS.";
global.ToThrowOrUseItems = " TO THROW OR USE ITEMS.";
global.HoldUpToThrowHighAndDownToDrop = "HOLD UP TO THROW HIGH AND DOWN TO DROP.";
global.ToSelectYourRopeAnd = " TO SELECT YOUR ROPE AND";
global.ToUseIt = " TO USE IT.";
global.CrouchAndPress = "CROUCH AND PRESS ";
global.ToThrowARopeDownALedge = "TO THROW A ROPE DOWN A LEDGE.";
global.ToRunHoldDown = "TO RUN, HOLD DOWN ";
global.Or = " OR ";
global.OpenThisCrateForABagOfBombs = "OPEN THIS CRATE FOR A BAG OF BOMBS.";
global.ToSelectBombsAnd = " TO SELECT BOMBS AND ";
global.ThereSLotsMoreAhead = "THERE'S LOTS MORE AHEAD!";
global.UseYourWitsAndBewareOfTraps = "USE YOUR WITS AND BEWARE OF TRAPS!";
global.PressUpToEnter = "PRESS UP TO ENTER!";
global.AsTheMoonBurnedBrightAbove = "AS THE MOON BURNED BRIGHT ABOVE,";
global.WithTheDesertStretchingBehindMe = "WITH THE DESERT STRETCHING BEHIND ME,";
global.AfterIDoubleCheckedMyMap = "AFTER I DOUBLE-CHECKED MY MAP,";
global.MyLipsCrackedAndCoveredInSand = "MY LIPS CRACKED AND COVERED IN SAND,";
global.WithFateGuidingMyEveryMove = "WITH FATE GUIDING MY EVERY MOVE,";
global.PuttingTheFadedPhotoInMyPocket = "PUTTING THE FADED PHOTO IN MY POCKET,";
global.AsIRecalledMyFatherSLastWords = "AS I RECALLED MY FATHER'S LAST WORDS,";
global.MyMemorySlippingAwayFromMe = "MY MEMORY SLIPPING AWAY FROM ME,";
global.IStrodeValiantlyTowardMyDestiny = "I STRODE VALIANTLY TOWARD MY DESTINY,";
global.ISqueezedTheWhipAtMySide = "I SQUEEZED THE WHIP AT MY SIDE,";
global.IDrainedTheRestOfMyCanteen = "I DRAINED THE REST OF MY CANTEEN,";
global.ISpottedTheCaveSEntrance = "I SPOTTED THE CAVE'S ENTRANCE,";
global.IFurrowedMyBrow = "I FURROWED MY BROW,";
global.IPaidMyBedouinGuide = "I PAID MY BEDOUIN GUIDE,";
global.IDismountedMyCamel = "I DISMOUNTED MY CAMEL,";
global.ISquintedIntoTheDarkness = "I SQUINTED INTO THE DARKNESS,";
global.AndThoughtOfHerOneLastTime = "AND THOUGHT OF HER ONE LAST TIME.";
global.AndHeldMyHatAgainstTheWind = "AND HELD MY HAT AGAINST THE WIND.";
global.AndAColdChillTookHoldOfMe = "AND A COLD CHILL TOOK HOLD OF ME.";
global.AndWonderedHowLongIDBeBelow = "AND WONDERED HOW LONG I'D BE BELOW.";
global.AndVowedToReturnVictorious = "AND VOWED TO RETURN VICTORIOUS.";
global.AndSworeIHeardVoicesUpAhead = "AND SWORE I HEARD VOICES UP AHEAD.";
global.AndFeltTheGodsSmilingUponMe = "AND FELT THE GODS SMILING UPON ME.";
global.AndThatSWhenItAllStarted = "AND THAT'S WHEN IT ALL STARTED.";
global.AGameBy = "A GAME BY";
global.ThanksForPlaying = "THANKS FOR PLAYING!";
global.SeeYouNextAdventure = "SEE YOU NEXT ADVENTURE!";
global.YouMadeIt = "YOU MADE IT!";
global.YouShallBeRememberedAsAHero = "YOU SHALL BE REMEMBERED AS A HERO.";
global.LoadLevel = "LOAD LEVEL:";
global.Levels = "LEVELS";
global.NoSuchLevelExists = "NO SUCH LEVEL EXISTS!";
global.EditLevel = "EDIT LEVEL:";
global.Label = "LABEL:";
global.Message = "MESSAGE:";
global.LevelName = "LEVEL NAME:";
global.Author = "AUTHOR:";
global.Music = "MUSIC: ";
global.StartLife = "START LIFE:";
global.StartBombs = "START BOMBS:";
global.StartRope = "START ROPE:";
global.NextLevel = "NEXT LEVEL:";
global.SaveLevelYN = "SAVE LEVEL? (Y/N)";
global.WarningNoEntrance = "WARNING: NO ENTRANCE!";
global.WarningNoExit = "WARNING: NO EXIT!";
global.Ahkmed = "AHKMED";
global.Terry = "TERRY";
global.Smithy = "SMITHY";
global.Leon = "LEON";
global.Ali = "ALI";
global.Elbert = "ELBERT";
global.Kao = "KAO";
global.Duke = "DUKE";
global.Tony = "TONY";
global.Guert = "GUERT";
global.Pancho = "PANCHO";
global.Earl = "EARL";
global.Ivan = "IVAN";
global.Ollie = "OLLIE";
global.Spoony = "SPOONY";
global.Bob = "BOB";
global.Rudy = "RUDY";
global.Jimbo = "JIMBO";
global.Tor = "TOR";
global.Willy = "WILLY";
global.Hamish = "HAMISH";
global.Lazlo = "LAZLO";
global.Wang = "WANG";
global.Herbie = "HERBIE";
global.Andy = "ANDY";
global.Dong = "DONG";
global.Lemmy = "LEMMY";
global.Barney = "BARNEY";
global.Lou = "LOU";
global.Tarn = "TARN";
global.Slash = "SLASH";
global.Brom = "BROM";
global.F4Controls = "F4 - CONTROLS";
global.Time3 = "TIME  = ";
global.Loot = "LOOT  = ";
global.Kills3 = "KILLS = ";
global.Money3 = "MONEY = ";
global.Time4 = "TIME";
global.Money4 = "MONEY";
global.Kills4 = "KILLS";
global.Saves2 = "SAVES";
global.Wins2 = "WINS";
global.Deaths2 = "DEATHS";
global.Tunnel1 = "TUNNEL1";
global.Tunnel2 = "TUNNEL2";
global.Minigames = "MINIGAMES";
global.MusicBy = "MUSIC BY";
global.PlatformEngine = "PLATFORM ENGINE";
global.SoundEffectsMadeUsing = "SOUND EFFECTS MADE USING";
global.ScreenScalingCode = "SCREEN SCALING CODE";
global.BetaTestingBy = "BETA TESTING BY";
global.PressKeyFor = "PRESS KEY FOR";
global.EscToKeepSame = "ESC TO KEEP SAME.";
global.Current = "CURRENT: ";
global.Up = "UP";
global.Down = "DOWN";
global.Left = "LEFT";
global.Right = "RIGHT";
global.Jump = "JUMP";
global.Action = "ACTION";
global.Switch = "SWITCH";
global.Run = "RUN";
global.Bomb = "BOMB";
global.Rope = "ROPE";
global.Flare = "FLARE";
global.Purchase = "PURCHASE";
global.UpArr = "UP ARR";
global.DownArr = "DOWN ARR";
global.LeftArr = "LEFT ARR";
global.RightArr = "RIGHT ARR";

/////////////////////////////////////////////////////////////////////////////////

if (global.lang != "En")
{
    file = file_text_open_read(trans_dir + "/text");
    if (file)
    {
        global.DerekYuPresents = file_text_read_string(file);
        file_text_readln(file);
        global.BetterLuckNextTime = file_text_read_string(file);
        file_text_readln(file);
        global.FinalScore = file_text_read_string(file);
        file_text_readln(file);
        global.ForHighScores = file_text_read_string(file);
        file_text_readln(file);
        global.GameOver = file_text_read_string(file);
        file_text_readln(file);
        global.Finished = file_text_read_string(file);
        file_text_readln(file);
        global.YouSetANewRecord = file_text_read_string(file);
        file_text_readln(file);
        global.Paused = file_text_read_string(file);
        file_text_readln(file);
        global.EcsReturnF1DieF10Quit = file_text_read_string(file);
        file_text_readln(file);
        global.StartReturnBombDieRopeQuit = file_text_read_string(file);
        file_text_readln(file);
        global.EscReturnF10Quit = file_text_read_string(file);
        file_text_readln(file);
        global.StartReturnRopeQuit = file_text_read_string(file);
        file_text_readln(file);
        global.ToEditLevel = file_text_read_string(file);
        file_text_readln(file);
        global.ToLoadAnotherLevel = file_text_read_string(file);
        file_text_readln(file);
        global.WelcomeToTheShortcutHouse = file_text_read_string(file);
        file_text_readln(file);
        global.Completed = file_text_read_string(file);
        file_text_readln(file);
        global.Depth = file_text_read_string(file);
        file_text_readln(file);
        global.Feet = file_text_read_string(file);
        file_text_readln(file);
        global.ForANewShortcut = file_text_read_string(file);
        file_text_readln(file);
        global.Level = file_text_read_string(file);
        file_text_readln(file);
        global.Kills = file_text_read_string(file);
        file_text_readln(file);
        global.Loot = file_text_read_string(file);
        file_text_readln(file);
        global.Time = file_text_read_string(file);
        file_text_readln(file);
        global.Money = file_text_read_string(file);
        file_text_readln(file);
        global.None = file_text_read_string(file);
        file_text_readln(file);
        global.MyHero = file_text_read_string(file);
        file_text_readln(file);
        global.OneShortcutComingUp = file_text_read_string(file);
        file_text_readln(file);
        global.IDigShortcuts = file_text_read_string(file);
        file_text_readln(file);
        global.Donate = file_text_read_string(file);
        file_text_readln(file);
        global.HeyThereImTheTunnelMan = file_text_read_string(file);
        file_text_readln(file);
        global.CanYouLendMeALittleMoney = file_text_read_string(file);
        file_text_readln(file);
        global.INeedS = file_text_read_string(file);
        file_text_readln(file);
        global.IllNeverGetThisShortcutBuilt = file_text_read_string(file);
        file_text_readln(file);
        global.ThanksYouWontRegretIt = file_text_read_string(file);
        file_text_readln(file);
        global.TutorialCaveCompleted = file_text_read_string(file);
        file_text_readln(file);
        global.SArmory = file_text_read_string(file);
        file_text_readln(file);
        global.SBombShop = file_text_read_string(file);
        file_text_readln(file);
        global.SClothingShop = file_text_read_string(file);
        file_text_readln(file);
        global.SDiceHouse = file_text_read_string(file);
        file_text_readln(file);
        global.ImSorryButYouLose = file_text_read_string(file);
        file_text_readln(file);
        global.CongratulationsYouWin = file_text_read_string(file);
        file_text_readln(file);
        global.GetOuttaHereDeadbeat = file_text_read_string(file);
        file_text_readln(file);
        global.NowAintHeSweet = file_text_read_string(file);
        file_text_readln(file);
        global.IHaveSomethingSpecial = file_text_read_string(file);
        file_text_readln(file);
        global.SKissingParlor = file_text_read_string(file);
        file_text_readln(file);
        global.AKissPress = file_text_read_string(file);
        file_text_readln(file);
        global.YouHaventGotEnoughMoney = file_text_read_string(file);
        file_text_readln(file);
        global.NowRollTheDice = file_text_read_string(file);
        file_text_readln(file);
        global.OneBetAtATime = file_text_read_string(file);
        file_text_readln(file);
        global.PleaseRollTheDice = file_text_read_string(file);
        file_text_readln(file);
        global.PleasureDoingBusiness = file_text_read_string(file);
        file_text_readln(file);
        global.YouRolledASeven = file_text_read_string(file);
        file_text_readln(file);
        global.NowAintSheSweet = file_text_read_string(file);
        file_text_readln(file);
        global.ComeBackHereThief = file_text_read_string(file);
        file_text_readln(file);
        global.DieYouVandal = file_text_read_string(file);
        file_text_readln(file);
        global.Terrorist = file_text_read_string(file);
        file_text_readln(file);
        global.HeqOnlyICanDoThat = file_text_read_string(file);
        file_text_readln(file);
        global.NowImReallySteamed = file_text_read_string(file);
        file_text_readln(file);
        global.YoullPayForYourCrimes = file_text_read_string(file);
        file_text_readln(file);
        global.SSpecialityShop = file_text_read_string(file);
        file_text_readln(file);
        global.SSupplyShop = file_text_read_string(file);
        file_text_readln(file);
        global.ToBetS = file_text_read_string(file);
        file_text_readln(file);
        global.ToPurchase = file_text_read_string(file);
        file_text_readln(file);
        global.WelcomeTo = file_text_read_string(file);
        file_text_readln(file);
        global.YouWonAPrize = file_text_read_string(file);
        file_text_readln(file);
        global.YouBetS = file_text_read_string(file);
        file_text_readln(file);
        global.YouNeedS = file_text_read_string(file);
        file_text_readln(file);
        global.YouRolledA = file_text_read_string(file);
        file_text_readln(file);
        global.YouFeelProtected = file_text_read_string(file);
        file_text_readln(file);
        global.YouGotTheAnkh = file_text_read_string(file);
        file_text_readln(file);
        global.AnAnkhForS = file_text_read_string(file);
        file_text_readln(file);
        global.YouGot3MoreBombs = file_text_read_string(file);
        file_text_readln(file);
        global.ABagOf3BombsForS = file_text_read_string(file);
        file_text_readln(file);
        global.YouGot12MoreBombs = file_text_read_string(file);
        file_text_readln(file);
        global.ABoxOf12BombsForS = file_text_read_string(file);
        file_text_readln(file);
        global.YouGotTheBowAndArrows = file_text_read_string(file);
        file_text_readln(file);
        global.BowAndArrowsForS = file_text_read_string(file);
        file_text_readln(file);
        global.YouGotACape = file_text_read_string(file);
        file_text_readln(file);
        global.ACapeForS = file_text_read_string(file);
        file_text_readln(file);
        global.YouGotACompass = file_text_read_string(file);
        file_text_readln(file);
        global.ACompassForS = file_text_read_string(file);
        file_text_readln(file);
        global.YouGotClimbingGloves = file_text_read_string(file);
        file_text_readln(file);
        global.ClimbingGlovesForS = file_text_read_string(file);
        file_text_readln(file);
        global.YourSpiderSenseTingles = file_text_read_string(file);
        file_text_readln(file);
        global.ItGlowsABrilliantWhite = file_text_read_string(file);
        file_text_readln(file);
        global.YouGotTheHedjet = file_text_read_string(file);
        file_text_readln(file);
        global.YouGotAJetpack = file_text_read_string(file);
        file_text_readln(file);
        global.JetpackForS = file_text_read_string(file);
        file_text_readln(file);
        global.YouFeelLightOnYourFeet = file_text_read_string(file);
        file_text_readln(file);
        global.YouGotJordans = file_text_read_string(file);
        file_text_readln(file);
        global.JordansForS50000 = file_text_read_string(file);
        file_text_readln(file);
        global.ItThirstsForBlood = file_text_read_string(file);
        file_text_readln(file);
        global.YouGotTheKapala = file_text_read_string(file);
        file_text_readln(file);
        global.YouGotAMachete = file_text_read_string(file);
        file_text_readln(file);
        global.AMacheteForS = file_text_read_string(file);
        file_text_readln(file);
        global.ItSeemsABitRusty = file_text_read_string(file);
        file_text_readln(file);
        global.YouGotAMattock = file_text_read_string(file);
        file_text_readln(file);
        global.AMattockForS = file_text_read_string(file);
        file_text_readln(file);
        global.ItWillDeployAutomatically = file_text_read_string(file);
        file_text_readln(file);
        global.YouGotAParachute = file_text_read_string(file);
        file_text_readln(file);
        global.AParachuteForS = file_text_read_string(file);
        file_text_readln(file);
        global.YouGotStickyBombs = file_text_read_string(file);
        file_text_readln(file);
        global.BombPasteForS = file_text_read_string(file);
        file_text_readln(file);
        global.YouGotAPistol = file_text_read_string(file);
        file_text_readln(file);
        global.APistolForS = file_text_read_string(file);
        file_text_readln(file);
        global.YouGotAPitcherSMitt = file_text_read_string(file);
        file_text_readln(file);
        global.PitcherSMittForS = file_text_read_string(file);
        file_text_readln(file);
        global.YouGot3MoreRopes = file_text_read_string(file);
        file_text_readln(file);
        global.ExtraRopeForS = file_text_read_string(file);
        file_text_readln(file);
        global.YouGotAShotgun = file_text_read_string(file);
        file_text_readln(file);
        global.AShotgunForS = file_text_read_string(file);
        file_text_readln(file);
        global.YourEyesightSeemsImproved = file_text_read_string(file);
        file_text_readln(file);
        global.YouGotSpectacles = file_text_read_string(file);
        file_text_readln(file);
        global.SpectaclesForS = file_text_read_string(file);
        file_text_readln(file);
        global.YouGotSpikeShoes = file_text_read_string(file);
        file_text_readln(file);
        global.SpikeShoesForS = file_text_read_string(file);
        file_text_readln(file);
        global.YouFeelBouncy = file_text_read_string(file);
        file_text_readln(file);
        global.YouGotSpringShoes = file_text_read_string(file);
        file_text_readln(file);
        global.SpringyShoesForS = file_text_read_string(file);
        file_text_readln(file);
        global.YouMustBeInLove = file_text_read_string(file);
        file_text_readln(file);
        global.YouGotATeleporter = file_text_read_string(file);
        file_text_readln(file);
        global.ATeleporterForS = file_text_read_string(file);
        file_text_readln(file);
        global.YouFeelAwakened = file_text_read_string(file);
        file_text_readln(file);
        global.YouGotTheUdjatEye = file_text_read_string(file);
        file_text_readln(file);
        global.YouGotAWebCannon = file_text_read_string(file);
        file_text_readln(file);
        global.AWebCannonForS = file_text_read_string(file);
        file_text_readln(file);
        global.YouHaveBeenRevived = file_text_read_string(file);
        file_text_readln(file);
        global.TheAnkhShatters = file_text_read_string(file);
        file_text_readln(file);
        global.PressEscapeToReturnToTitle = file_text_read_string(file);
        file_text_readln(file);
        global.IMOutOfArrows = file_text_read_string(file);
        file_text_readln(file);
        global.Press = file_text_read_string(file);
        file_text_readln(file);
        global.ButNothingIsHappening = file_text_read_string(file);
        file_text_readln(file);
        global.TheSceptreFits = file_text_read_string(file);
        file_text_readln(file);
        global.SheSeemsVeryAngryWithYou = file_text_read_string(file);
        file_text_readln(file);
        global.SheSeemsAngryWithYou = file_text_read_string(file);
        file_text_readln(file);
        global.SheHasForgivenYou = file_text_read_string(file);
        file_text_readln(file);
        global.YouFeelInvigorated = file_text_read_string(file);
        file_text_readln(file);
        global.SheSeemsEcstaticWithYou = file_text_read_string(file);
        file_text_readln(file);
        global.YourSatchelFeelsVeryFullNow = file_text_read_string(file);
        file_text_readln(file);
        global.SheSeemsVeryHappyWithYou = file_text_read_string(file);
        file_text_readln(file);
        global.SheSeemsHappyWithYou = file_text_read_string(file);
        file_text_readln(file);
        global.SheBestowsAGiftUponYou = file_text_read_string(file);
        file_text_readln(file);
        global.SheSeemsPleasedWithYou = file_text_read_string(file);
        file_text_readln(file);
        global.KaliAcceptsTheSacrifice = file_text_read_string(file);
        file_text_readln(file);
        global.KaliDevoursTheSacrifice = file_text_read_string(file);
        file_text_readln(file);
        global.YouDareDefileMyAltar = file_text_read_string(file);
        file_text_readln(file);
        global.IWillPunishYou = file_text_read_string(file);
        file_text_readln(file);
        global.AChillRunsUpYourSpine = file_text_read_string(file);
        file_text_readln(file);
        global.LetSGetOutOfHere = file_text_read_string(file);
        file_text_readln(file);
        global.ThereSAPsychicPresenceHere = file_text_read_string(file);
        file_text_readln(file);
        global.IDBetterUseTheseFlares = file_text_read_string(file);
        file_text_readln(file);
        global.WelcomeToTheBlackMarket = file_text_read_string(file);
        file_text_readln(file);
        global.ICanTSeeAThing = file_text_read_string(file);
        file_text_readln(file);
        global.TheDeadAreRestless = file_text_read_string(file);
        file_text_readln(file);
        global.ItSTheLegendaryCityOfGold = file_text_read_string(file);
        file_text_readln(file);
        global.TheHedjetShinesBrightly = file_text_read_string(file);
        file_text_readln(file);
        global.ICanHearRushingWater = file_text_read_string(file);
        file_text_readln(file);
        global.ICanHearPrayersToKali = file_text_read_string(file);
        file_text_readln(file);
        global.IHearSnakesIHateSnakes = file_text_read_string(file);
        file_text_readln(file);
        global.ItSmellsLikeWetFurInHere = file_text_read_string(file);
        file_text_readln(file);
        global.SecretChallenges = file_text_read_string(file);
        file_text_readln(file);
        global.Sun = file_text_read_string(file);
        file_text_readln(file);
        global.Moon = file_text_read_string(file);
        file_text_readln(file);
        global.Stars = file_text_read_string(file);
        file_text_readln(file);
        global.SunRoom = file_text_read_string(file);
        file_text_readln(file);
        global.KeepYourselfAnd = file_text_read_string(file);
        file_text_readln(file);
        global.TheDamselAlive = file_text_read_string(file);
        file_text_readln(file);
        global.ForAsLongAs = file_text_read_string(file);
        file_text_readln(file);
        global.Possible = file_text_read_string(file);
        file_text_readln(file);
        global.DamselChallengeBeginsIn = file_text_read_string(file);
        file_text_readln(file);
        global.Locked = file_text_read_string(file);
        file_text_readln(file);
        global.MoonRoom = file_text_read_string(file);
        file_text_readln(file);
        global.ShootTheMoving = file_text_read_string(file);
        file_text_readln(file);
        global.TargetsWithYour = file_text_read_string(file);
        file_text_readln(file);
        global.BowAndArrows = file_text_read_string(file);
        file_text_readln(file);
        global.ArcheryChallengeBeginsIn = file_text_read_string(file);
        file_text_readln(file);
        global.StarsRoom = file_text_read_string(file);
        file_text_readln(file);
        global.KillAsManyAngry = file_text_read_string(file);
        file_text_readln(file);
        global.ShopkeepsAsYouCan = file_text_read_string(file);
        file_text_readln(file);
        global.BeforeTheyGetYou = file_text_read_string(file);
        file_text_readln(file);
        global.ShotgunChallengeBeginsIn = file_text_read_string(file);
        file_text_readln(file);
        global.ChangingRoom = file_text_read_string(file);
        file_text_readln(file);
        global.LadyInRed = file_text_read_string(file);
        file_text_readln(file);
        global.TopDefilers = file_text_read_string(file);
        file_text_readln(file);
        global.Money2 = file_text_read_string(file);
        file_text_readln(file);
        global.Kills2 = file_text_read_string(file);
        file_text_readln(file);
        global.Saves = file_text_read_string(file);
        file_text_readln(file);
        global.Time2 = file_text_read_string(file);
        file_text_readln(file);
        global.Plays = file_text_read_string(file);
        file_text_readln(file);
        global.Deaths = file_text_read_string(file);
        file_text_readln(file);
        global.Wins = file_text_read_string(file);
        file_text_readln(file);
        global.Statistics = file_text_read_string(file);
        file_text_readln(file);
        global.ThisWillClearEverything = file_text_read_string(file);
        file_text_readln(file);
        global.ToJump = file_text_read_string(file);
        file_text_readln(file);
        global.ToUseYourWhip = file_text_read_string(file);
        file_text_readln(file);
        global.HoldUpAndPress = file_text_read_string(file);
        file_text_readln(file);
        global.WelcomeToTheTutorialCave = file_text_read_string(file);
        file_text_readln(file);
        global.ThisMightBeYourFirstTimePlaying = file_text_read_string(file);
        file_text_readln(file);
        global.YouCanHangOnLedgesToo = file_text_read_string(file);
        file_text_readln(file);
        global.CollectTheTreasure = file_text_read_string(file);
        file_text_readln(file);
        global.ToOpenChests = file_text_read_string(file);
        file_text_readln(file);
        global.HoldDownToDuckAndCrawl = file_text_read_string(file);
        file_text_readln(file);
        global.CrawlOverTheEdgeToDoAFlipHang = file_text_read_string(file);
        file_text_readln(file);
        global.FallingTooFarCanReallyHurt = file_text_read_string(file);
        file_text_readln(file);
        global.HoldUpToClimbTheLadder = file_text_read_string(file);
        file_text_readln(file);
        global.DuckAndPress = file_text_read_string(file);
        file_text_readln(file);
        global.ToPickUpItems = file_text_read_string(file);
        file_text_readln(file);
        global.ToThrowOrUseItems = file_text_read_string(file);
        file_text_readln(file);
        global.HoldUpToThrowHighAndDownToDrop = file_text_read_string(file);
        file_text_readln(file);
        global.ToSelectYourRopeAnd = file_text_read_string(file);
        file_text_readln(file);
        global.ToUseIt = file_text_read_string(file);
        file_text_readln(file);
        global.CrouchAndPress = file_text_read_string(file);
        file_text_readln(file);
        global.ToThrowARopeDownALedge = file_text_read_string(file);
        file_text_readln(file);
        global.ToRunHoldDown = file_text_read_string(file);
        file_text_readln(file);
        global.Or = file_text_read_string(file);
        file_text_readln(file);
        global.OpenThisCrateForABagOfBombs = file_text_read_string(file);
        file_text_readln(file);
        global.ToSelectBombsAnd = file_text_read_string(file);
        file_text_readln(file);
        global.ThereSLotsMoreAhead = file_text_read_string(file);
        file_text_readln(file);
        global.UseYourWitsAndBewareOfTraps = file_text_read_string(file);
        file_text_readln(file);
        global.PressUpToEnter = file_text_read_string(file);
        file_text_readln(file);
        global.AsTheMoonBurnedBrightAbove = file_text_read_string(file);
        file_text_readln(file);
        global.WithTheDesertStretchingBehindMe = file_text_read_string(file);
        file_text_readln(file);
        global.AfterIDoubleCheckedMyMap = file_text_read_string(file);
        file_text_readln(file);
        global.MyLipsCrackedAndCoveredInSand = file_text_read_string(file);
        file_text_readln(file);
        global.WithFateGuidingMyEveryMove = file_text_read_string(file);
        file_text_readln(file);
        global.PuttingTheFadedPhotoInMyPocket = file_text_read_string(file);
        file_text_readln(file);
        global.AsIRecalledMyFatherSLastWords = file_text_read_string(file);
        file_text_readln(file);
        global.MyMemorySlippingAwayFromMe = file_text_read_string(file);
        file_text_readln(file);
        global.IStrodeValiantlyTowardMyDestiny = file_text_read_string(file);
        file_text_readln(file);
        global.ISqueezedTheWhipAtMySide = file_text_read_string(file);
        file_text_readln(file);
        global.IDrainedTheRestOfMyCanteen = file_text_read_string(file);
        file_text_readln(file);
        global.ISpottedTheCaveSEntrance = file_text_read_string(file);
        file_text_readln(file);
        global.IFurrowedMyBrow = file_text_read_string(file);
        file_text_readln(file);
        global.IPaidMyBedouinGuide = file_text_read_string(file);
        file_text_readln(file);
        global.IDismountedMyCamel = file_text_read_string(file);
        file_text_readln(file);
        global.ISquintedIntoTheDarkness = file_text_read_string(file);
        file_text_readln(file);
        global.AndThoughtOfHerOneLastTime = file_text_read_string(file);
        file_text_readln(file);
        global.AndHeldMyHatAgainstTheWind = file_text_read_string(file);
        file_text_readln(file);
        global.AndAColdChillTookHoldOfMe = file_text_read_string(file);
        file_text_readln(file);
        global.AndWonderedHowLongIDBeBelow = file_text_read_string(file);
        file_text_readln(file);
        global.AndVowedToReturnVictorious = file_text_read_string(file);
        file_text_readln(file);
        global.AndSworeIHeardVoicesUpAhead = file_text_read_string(file);
        file_text_readln(file);
        global.AndFeltTheGodsSmilingUponMe = file_text_read_string(file);
        file_text_readln(file);
        global.AndThatSWhenItAllStarted = file_text_read_string(file);
        file_text_readln(file);
        global.AGameBy = file_text_read_string(file);
        file_text_readln(file);
        global.ThanksForPlaying = file_text_read_string(file);
        file_text_readln(file);
        global.SeeYouNextAdventure = file_text_read_string(file);
        file_text_readln(file);
        global.YouMadeIt = file_text_read_string(file);
        file_text_readln(file);
        global.YouShallBeRememberedAsAHero = file_text_read_string(file);
        file_text_readln(file);
        global.LoadLevel = file_text_read_string(file);
        file_text_readln(file);
        global.Levels = file_text_read_string(file);
        file_text_readln(file);
        global.NoSuchLevelExists = file_text_read_string(file);
        file_text_readln(file);
        global.EditLevel = file_text_read_string(file);
        file_text_readln(file);
        global.Label = file_text_read_string(file);
        file_text_readln(file);
        global.Message = file_text_read_string(file);
        file_text_readln(file);
        global.LevelName = file_text_read_string(file);
        file_text_readln(file);
        global.Author = file_text_read_string(file);
        file_text_readln(file);
        global.Music = file_text_read_string(file);
        file_text_readln(file);
        global.StartLife = file_text_read_string(file);
        file_text_readln(file);
        global.StartBombs = file_text_read_string(file);
        file_text_readln(file);
        global.StartRope = file_text_read_string(file);
        file_text_readln(file);
        global.NextLevel = file_text_read_string(file);
        file_text_readln(file);
        global.SaveLevelYN = file_text_read_string(file);
        file_text_readln(file);
        global.WarningNoEntrance = file_text_read_string(file);
        file_text_readln(file);
        global.WarningNoExit = file_text_read_string(file);
        file_text_readln(file);
        global.Ahkmed = file_text_read_string(file);
        file_text_readln(file);
        global.Terry = file_text_read_string(file);
        file_text_readln(file);
        global.Smithy = file_text_read_string(file);
        file_text_readln(file);
        global.Leon = file_text_read_string(file);
        file_text_readln(file);
        global.Ali = file_text_read_string(file);
        file_text_readln(file);
        global.Elbert = file_text_read_string(file);
        file_text_readln(file);
        global.Kao = file_text_read_string(file);
        file_text_readln(file);
        global.Duke = file_text_read_string(file);
        file_text_readln(file);
        global.Tony = file_text_read_string(file);
        file_text_readln(file);
        global.Guert = file_text_read_string(file);
        file_text_readln(file);
        global.Pancho = file_text_read_string(file);
        file_text_readln(file);
        global.Earl = file_text_read_string(file);
        file_text_readln(file);
        global.Ivan = file_text_read_string(file);
        file_text_readln(file);
        global.Ollie = file_text_read_string(file);
        file_text_readln(file);
        global.Spoony = file_text_read_string(file);
        file_text_readln(file);
        global.Bob = file_text_read_string(file);
        file_text_readln(file);
        global.Rudy = file_text_read_string(file);
        file_text_readln(file);
        global.Jimbo = file_text_read_string(file);
        file_text_readln(file);
        global.Tor = file_text_read_string(file);
        file_text_readln(file);
        global.Willy = file_text_read_string(file);
        file_text_readln(file);
        global.Hamish = file_text_read_string(file);
        file_text_readln(file);
        global.Lazlo = file_text_read_string(file);
        file_text_readln(file);
        global.Wang = file_text_read_string(file);
        file_text_readln(file);
        global.Herbie = file_text_read_string(file);
        file_text_readln(file);
        global.Andy = file_text_read_string(file);
        file_text_readln(file);
        global.Dong = file_text_read_string(file);
        file_text_readln(file);
        global.Lemmy = file_text_read_string(file);
        file_text_readln(file);
        global.Barney = file_text_read_string(file);
        file_text_readln(file);
        global.Lou = file_text_read_string(file);
        file_text_readln(file);
        global.Tarn = file_text_read_string(file);
        file_text_readln(file);
        global.Slash = file_text_read_string(file);
        file_text_readln(file);
        global.Brom = file_text_read_string(file);
        file_text_readln(file);
        global.F4Controls = file_text_read_string(file);
        file_text_readln(file);
        global.Time3 = file_text_read_string(file);
        file_text_readln(file);
        global.Loot = file_text_read_string(file);
        file_text_readln(file);
        global.Kills3 = file_text_read_string(file);
        file_text_readln(file);
        global.Money3 = file_text_read_string(file);
        file_text_readln(file);
        global.Time4 = file_text_read_string(file);
        file_text_readln(file);
        global.Money4 = file_text_read_string(file);
        file_text_readln(file);
        global.Kills4 = file_text_read_string(file);
        file_text_readln(file);
        global.Saves2 = file_text_read_string(file);
        file_text_readln(file);
        global.Wins2 = file_text_read_string(file);
        file_text_readln(file);
        global.Deaths2 = file_text_read_string(file);
        file_text_readln(file);
        global.Tunnel1 = file_text_read_string(file);
        file_text_readln(file);
        global.Tunnel2 = file_text_read_string(file);
        file_text_readln(file);
        global.Minigames = file_text_read_string(file);
        file_text_readln(file);
        global.MusicBy = file_text_read_string(file);
        file_text_readln(file);
        global.PlatformEngine = file_text_read_string(file);
        file_text_readln(file);
        global.SoundEffectsMadeUsing = file_text_read_string(file);
        file_text_readln(file);
        global.ScreenScalingCode = file_text_read_string(file);
        file_text_readln(file);
        global.BetaTestingBy = file_text_read_string(file);
        file_text_readln(file);
        global.PressKeyFor = file_text_read_string(file);
        file_text_readln(file);
        global.EscToKeepSame = file_text_read_string(file);
        file_text_readln(file);
        global.Current = file_text_read_string(file);
        file_text_readln(file);
        global.Up = file_text_read_string(file);
        file_text_readln(file);
        global.Down = file_text_read_string(file);
        file_text_readln(file);
        global.Left = file_text_read_string(file);
        file_text_readln(file);
        global.Right = file_text_read_string(file);
        file_text_readln(file);
        global.Jump = file_text_read_string(file);
        file_text_readln(file);
        global.Action = file_text_read_string(file);
        file_text_readln(file);
        global.Switch = file_text_read_string(file);
        file_text_readln(file);
        global.Run = file_text_read_string(file);
        file_text_readln(file);
        global.Bomb = file_text_read_string(file);
        file_text_readln(file);
        global.Rope = file_text_read_string(file);
        file_text_readln(file);
        global.Flare = file_text_read_string(file);
        file_text_readln(file);
        global.Purchase = file_text_read_string(file);
        file_text_readln(file);
        global.UpArr = file_text_read_string(file);
        file_text_readln(file);
        global.DownArr = file_text_read_string(file);
        file_text_readln(file);
        global.LeftArr = file_text_read_string(file);
        file_text_readln(file);
        global.RightArr = file_text_read_string(file);

        file_text_close(file);
    }
}
